<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="PRG_Statemachine" Id="{4f9187be-29d3-40ff-a8c0-93ee549dcec9}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_Statemachine
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <StateChart>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="UMLStateChart">
              <v n="Abortable">true</v>
              <v n="UseVarInstForMethods">false</v>
              <v n="StatesCount">12</v>
              <v n="HistoryCount">0</v>
              <v n="TransitionsCount">23</v>
              <v n="RegionsCount">0</v>
              <v n="TracesCount">0</v>
              <v n="StatesInitString">":=[(ID := 1, Name := 'GeneratedStartStateForAbort1', StateType := _UML_SC_StateTypes.InitialState, StartOfTransitionIndex := 1, OutGoingTransitionsCount := 1, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := False, HasDoAction := False, HasExitAction := False) , 
(ID := 2, Name := 'GeneratedFinalStateForAbort1', StateType := _UML_SC_StateTypes.FinalState, StartOfTransitionIndex := 0, OutGoingTransitionsCount := 0, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := False, HasDoAction := False, HasExitAction := False) , 
(ID := 3, Name := 'Reset', StateType := _UML_SC_StateTypes.SlowState, StartOfTransitionIndex := 2, OutGoingTransitionsCount := 2, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := True, HasDoAction := True, HasExitAction := False) , 
(ID := 4, Name := 'StartState1', StateType := _UML_SC_StateTypes.FastState, StartOfTransitionIndex := 4, OutGoingTransitionsCount := 1, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := False, HasDoAction := False, HasExitAction := False) , 
(ID := 5, Name := 'Preop', StateType := _UML_SC_StateTypes.SlowState, StartOfTransitionIndex := 5, OutGoingTransitionsCount := 2, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := True, HasDoAction := True, HasExitAction := False) , 
(ID := 6, Name := 'Error', StateType := _UML_SC_StateTypes.SlowState, StartOfTransitionIndex := 7, OutGoingTransitionsCount := 2, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := True, HasDoAction := True, HasExitAction := False) , 
(ID := 7, Name := 'Operation', StateType := _UML_SC_StateTypes.SlowState, StartOfTransitionIndex := 9, OutGoingTransitionsCount := 2, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := True, HasDoAction := False, HasExitAction := False) , 
(ID := 8, Name := 'Init', StateType := _UML_SC_StateTypes.SlowState, StartOfTransitionIndex := 11, OutGoingTransitionsCount := 2, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := True, HasDoAction := True, HasExitAction := False) , 
(ID := 9, Name := 'Ready', StateType := _UML_SC_StateTypes.SlowState, StartOfTransitionIndex := 13, OutGoingTransitionsCount := 2, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := True, HasDoAction := False, HasExitAction := False) , 
(ID := 10, Name := 'Init2', StateType := _UML_SC_StateTypes.SlowState, StartOfTransitionIndex := 15, OutGoingTransitionsCount := 3, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := False, HasDoAction := False, HasExitAction := False) , 
(ID := 11, Name := 'ChoiceElement1', StateType := _UML_SC_StateTypes.FastState, StartOfTransitionIndex := 18, OutGoingTransitionsCount := 3, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 0, HasEntryAction := False, HasDoAction := False, HasExitAction := False) , 
(ID := 12, Name := 'Finished', StateType := _UML_SC_StateTypes.SlowState, StartOfTransitionIndex := 21, OutGoingTransitionsCount := 3, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := True, HasDoAction := True, HasExitAction := False) ];
"</v>
              <v n="TransitionsInitString">":=[(ID := 1, StartStateID := 1, EndStateID := 4, Priority := 1, HasAction := False, IsCompletion := True,IsPseudoException := False,IsException := False), 
(ID := 2, StartStateID := 3, EndStateID := 2, Priority := 1, HasAction := True, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 3, StartStateID := 3, EndStateID := 10, Priority := 2, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 4, StartStateID := 4, EndStateID := 8, Priority := 1, HasAction := False, IsCompletion := True,IsPseudoException := False,IsException := False), 
(ID := 5, StartStateID := 5, EndStateID := 6, Priority := 1, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 6, StartStateID := 5, EndStateID := 11, Priority := 2, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 7, StartStateID := 6, EndStateID := 2, Priority := 1, HasAction := True, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 8, StartStateID := 6, EndStateID := 3, Priority := 2, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 9, StartStateID := 7, EndStateID := 6, Priority := 1, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 10, StartStateID := 7, EndStateID := 12, Priority := 2, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 11, StartStateID := 8, EndStateID := 2, Priority := 1, HasAction := True, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 12, StartStateID := 8, EndStateID := 10, Priority := 2, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 13, StartStateID := 9, EndStateID := 6, Priority := 1, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 14, StartStateID := 9, EndStateID := 7, Priority := 2, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 15, StartStateID := 10, EndStateID := 2, Priority := 1, HasAction := True, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 16, StartStateID := 10, EndStateID := 8, Priority := 2, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 17, StartStateID := 10, EndStateID := 5, Priority := 3, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 18, StartStateID := 11, EndStateID := 6, Priority := 1, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 19, StartStateID := 11, EndStateID := 9, Priority := 2, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 20, StartStateID := 11, EndStateID := 9, Priority := 3, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 21, StartStateID := 12, EndStateID := 6, Priority := 1, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 22, StartStateID := 12, EndStateID := 7, Priority := 2, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 23, StartStateID := 12, EndStateID := 9, Priority := 3, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False)];
"</v>
              <v n="RegionsInitString">""</v>
              <v n="StateNamesString">"GeneratedStartStateForAbort1:INT:=1;
GeneratedFinalStateForAbort1:INT:=2;
Reset:INT:=3;
StartState1:INT:=4;
Preop:INT:=5;
Error:INT:=6;
Operation:INT:=7;
Init:INT:=8;
Ready:INT:=9;
Init2:INT:=10;
ChoiceElement1:INT:=11;
Finished:INT:=12;
"</v>
              <n n="StateNamesInitString" />
              <v n="ForceActionRemove">false</v>
              <d n="RegionsWithStartStatesTable" t="Hashtable" ckt="Guid" cvt="Int32">
                <v>00000000-0000-0000-0000-000000000000</v>
                <v>1</v>
              </d>
              <d n="RegionsWithHistoryStatesTable" t="Hashtable" ckt="Guid" cvt="Int32">
                <v>00000000-0000-0000-0000-000000000000</v>
                <v>1</v>
              </d>
              <d n="RegionsWithEndStatesTable" t="Hashtable" />
              <n n="BreakPointGuids" />
              <v n="UmlEditorRestrictions" t="EditorRestrictions">None</v>
              <v n="DUTObjectGuid">{3fb1819c-12c4-4313-8178-54f4f30decb2}</v>
              <v n="DUTNamesObjectGuid">{4887688d-9a63-449c-a945-730b4d7ce016}</v>
              <v n="TraceObject">{00000000-0000-0000-0000-000000000000}</v>
              <v n="IsCompiling">false</v>
              <v n="HideLanguageModel">false</v>
              <v n="DefaultStateSizeX">62</v>
              <v n="DefaultStateSizeY">32</v>
              <v n="SuppressAutomaticLibraryLoading">false</v>
              <v n="DiagramName">"PRG_Statemachine"</v>
              <v n="DiagramGuid">{4f9187be-29d3-40ff-a8c0-93ee549dcec9}</v>
              <v n="IsActionRemoving">false</v>
              <v n="ForceRepaintDiagram">false</v>
              <v n="Documentationdiagram">false</v>
              <v n="ApplicationGuidForDiagram">{00000000-0000-0000-0000-000000000000}</v>
              <v n="AutomaticLayOutHeightSpace">0</v>
              <v n="AutomaticLayOutWidthSpace">0</v>
              <d n="ElementObjects" t="Hashtable" ckt="Guid">
                <v>d1aa34d3-82ff-46d3-a87c-3bddaa010424</v>
                <o t="UMLStateChartElement">
                  <v n="StateChartGuid">{4f9187be-29d3-40ff-a8c0-93ee549dcec9}</v>
                  <v n="ImplicitStartStateType" t="ImplicitStartStateTypes">None</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">"PRG_Statemachine_Init_ENTRY"</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">"PRG_Statemachine_Init_ENTRY"</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">"PRG_Statemachine_Init_DO"</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">"PRG_Statemachine_Init_DO"</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">true</v>
                  <v n="HasDoAction">true</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"Init"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <o n="ElementVisualisation" t="UMLStateChartElementVisualisation">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">180</v>
                    <v n="LeftPosition">50</v>
                    <v n="WidthValue">234</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">66</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartElement</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">62</v>
                  <v n="DefaultCellSizeY">32</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{d1aa34d3-82ff-46d3-a87c-3bddaa010424}</v>
                  <v n="ParentGuid">{4f9187be-29d3-40ff-a8c0-93ee549dcec9}</v>
                  <v n="ContainerGuid">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ShowedStereotype">{cd9e95f9-f26c-4d1a-9964-bd7a1ee69db2}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">-13447886</v>
                  <v n="ZOrder">82U</v>
                </o>
                <v>79e2950d-15d4-4eef-892e-5f057e8ea4ef</v>
                <o t="UMLStateChartElement">
                  <v n="StateChartGuid">{4f9187be-29d3-40ff-a8c0-93ee549dcec9}</v>
                  <v n="ImplicitStartStateType" t="ImplicitStartStateTypes">None</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">"PRG_Statemachine_Error_ENTRY"</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">"PRG_Statemachine_Error_ENTRY"</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">"PRG_Statemachine_Error_DO"</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">"PRG_Statemachine_Error_DO"</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">true</v>
                  <v n="HasDoAction">true</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"Error"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <o n="ElementVisualisation" t="UMLStateChartElementVisualisation">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">2</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">450</v>
                    <v n="LeftPosition">1150</v>
                    <v n="WidthValue">244</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">66</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartElement</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">62</v>
                  <v n="DefaultCellSizeY">32</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">2</v>
                  <v n="ElementObjectGuid">{79e2950d-15d4-4eef-892e-5f057e8ea4ef}</v>
                  <v n="ParentGuid">{4f9187be-29d3-40ff-a8c0-93ee549dcec9}</v>
                  <v n="ContainerGuid">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ShowedStereotype">{8bb0cce1-49f6-45ff-a7c1-5c93eaf64302}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">-13447886</v>
                  <v n="ZOrder">58U</v>
                </o>
                <v>d8bcd792-7416-4b04-81cc-5288d36a3db3</v>
                <o t="UMLStateChartElement">
                  <v n="StateChartGuid">{4f9187be-29d3-40ff-a8c0-93ee549dcec9}</v>
                  <v n="ImplicitStartStateType" t="ImplicitStartStateTypes">None</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">"PRG_Statemachine_Ready_ENTRY"</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">"PRG_Statemachine_Ready_ENTRY"</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">""</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">""</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">true</v>
                  <v n="HasDoAction">false</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"Ready"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <o n="ElementVisualisation" t="UMLStateChartElementVisualisation">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">150</v>
                    <v n="LeftPosition">1450</v>
                    <v n="WidthValue">251</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">49</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartElement</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">62</v>
                  <v n="DefaultCellSizeY">32</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{56375e9c-dc75-4f03-b1e8-7503465560d1}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{d8bcd792-7416-4b04-81cc-5288d36a3db3}</v>
                  <v n="ParentGuid">{4f9187be-29d3-40ff-a8c0-93ee549dcec9}</v>
                  <v n="ContainerGuid">{03b9b18d-3155-41e0-a205-42a30c935f65}</v>
                  <v n="ShowedStereotype">{c96b9c62-1c86-45a1-b2af-8ad0933237eb}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">-13447886</v>
                  <v n="ZOrder">93U</v>
                </o>
                <v>ee5525d9-045e-430a-80e8-849f90fcfd9d</v>
                <o t="UMLStateChartElement">
                  <v n="StateChartGuid">{4f9187be-29d3-40ff-a8c0-93ee549dcec9}</v>
                  <v n="ImplicitStartStateType" t="ImplicitStartStateTypes">None</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">""</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">""</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">""</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">""</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">true</v>
                  <v n="HasDoAction">false</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"Init2"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <o n="ElementVisualisation" t="UMLStateChartElementVisualisation">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">180</v>
                    <v n="LeftPosition">550</v>
                    <v n="WidthValue">70</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">49</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartElement</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">62</v>
                  <v n="DefaultCellSizeY">32</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{ee5525d9-045e-430a-80e8-849f90fcfd9d}</v>
                  <v n="ParentGuid">{4f9187be-29d3-40ff-a8c0-93ee549dcec9}</v>
                  <v n="ContainerGuid">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ShowedStereotype">{1ccecfa9-8d9f-4321-a053-c3d50794e55b}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">-13447886</v>
                  <v n="ZOrder">99U</v>
                </o>
                <v>2b796e83-5356-4d20-b83b-8d0e8e6cf8c6</v>
                <o t="UMLStateChartElement">
                  <v n="StateChartGuid">{4f9187be-29d3-40ff-a8c0-93ee549dcec9}</v>
                  <v n="ImplicitStartStateType" t="ImplicitStartStateTypes">None</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">"PRG_Statemachine_Reset_ENTRY"</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">"PRG_Statemachine_Reset_ENTRY"</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">"PRG_Statemachine_Reset_DO"</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">"PRG_Statemachine_Reset_DO"</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">true</v>
                  <v n="HasDoAction">true</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"Reset"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <o n="ElementVisualisation" t="UMLStateChartElementVisualisation">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">420</v>
                    <v n="LeftPosition">660</v>
                    <v n="WidthValue">248</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">66</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartElement</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">62</v>
                  <v n="DefaultCellSizeY">32</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{2b796e83-5356-4d20-b83b-8d0e8e6cf8c6}</v>
                  <v n="ParentGuid">{4f9187be-29d3-40ff-a8c0-93ee549dcec9}</v>
                  <v n="ContainerGuid">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ShowedStereotype">{1d5559c2-a0c5-47f2-8473-6e8d58b0f70b}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">-13447886</v>
                  <v n="ZOrder">72U</v>
                </o>
                <v>322ae633-3183-4716-b79d-ed73d6d304b5</v>
                <o t="UMLStateChartPseudoElement">
                  <o n="ElementVisualisation" t="UMLStateChartDiagramElementVisualisationDot">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">10</v>
                    <v n="LeftPosition">120</v>
                    <v n="WidthValue">20</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">20</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <v n="Condition">""</v>
                  <v n="HistoryType" t="HistoryTypes">None</v>
                  <v n="StateChartGuid">{4f9187be-29d3-40ff-a8c0-93ee549dcec9}</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">""</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">""</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">""</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">""</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">false</v>
                  <v n="HasDoAction">false</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"StartState1"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartStartState</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">20</v>
                  <v n="DefaultCellSizeY">20</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{322ae633-3183-4716-b79d-ed73d6d304b5}</v>
                  <v n="ParentGuid">{4f9187be-29d3-40ff-a8c0-93ee549dcec9}</v>
                  <v n="ContainerGuid">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ShowedStereotype">{d854efaf-3f66-41dd-8f43-7b5cffbbad41}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                  <v n="ZOrder">91U</v>
                </o>
                <v>f872b14a-0555-4bb5-ab12-654b6f61a846</v>
                <o t="UMLStateChartPseudoElement">
                  <o n="ElementVisualisation" t="UMLStateChartDiagramElementVisualisationDot">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">140</v>
                    <v n="LeftPosition">1270</v>
                    <v n="WidthValue">20</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">20</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <v n="Condition">""</v>
                  <v n="HistoryType" t="HistoryTypes">None</v>
                  <v n="StateChartGuid">{4f9187be-29d3-40ff-a8c0-93ee549dcec9}</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">""</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">""</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">""</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">""</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">false</v>
                  <v n="HasDoAction">false</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"ChoiceElement1"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartChoice</v>
                  <v n="_MaxDoCycleCalls" t="Int16">1</v>
                  <v n="DefaultCellSizeX">20</v>
                  <v n="DefaultCellSizeY">20</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{56375e9c-dc75-4f03-b1e8-7503465560d1}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{f872b14a-0555-4bb5-ab12-654b6f61a846}</v>
                  <v n="ParentGuid">{4f9187be-29d3-40ff-a8c0-93ee549dcec9}</v>
                  <v n="ContainerGuid">{03b9b18d-3155-41e0-a205-42a30c935f65}</v>
                  <v n="ShowedStereotype">{b281ec36-3447-4870-a6ef-16b4d693ac90}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                  <v n="ZOrder">95U</v>
                </o>
                <v>fcc12a7a-0758-465a-b3e9-e9ed2b5e6f97</v>
                <o t="UMLStateChartElement">
                  <v n="StateChartGuid">{4f9187be-29d3-40ff-a8c0-93ee549dcec9}</v>
                  <v n="ImplicitStartStateType" t="ImplicitStartStateTypes">None</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">"PRG_Statemachine_Finished_ENTRY"</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">"PRG_Statemachine_Finished_ENTRY"</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">"PRG_Statemachine_Finished_DO"</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">"PRG_Statemachine_Finished_DO"</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">true</v>
                  <v n="HasDoAction">true</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"Finished"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <o n="ElementVisualisation" t="UMLStateChartElementVisualisation">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">320</v>
                    <v n="LeftPosition">980</v>
                    <v n="WidthValue">261</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">66</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartElement</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">62</v>
                  <v n="DefaultCellSizeY">32</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{56375e9c-dc75-4f03-b1e8-7503465560d1}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{fcc12a7a-0758-465a-b3e9-e9ed2b5e6f97}</v>
                  <v n="ParentGuid">{4f9187be-29d3-40ff-a8c0-93ee549dcec9}</v>
                  <v n="ContainerGuid">{03b9b18d-3155-41e0-a205-42a30c935f65}</v>
                  <v n="ShowedStereotype">{d31a41b1-06f2-4d09-af54-1643dfba3ccb}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">-13447886</v>
                  <v n="ZOrder">96U</v>
                </o>
                <v>4d2ac672-37ee-4b10-b8f4-30c19cd79fcb</v>
                <o t="UMLStateChartElement">
                  <v n="StateChartGuid">{4f9187be-29d3-40ff-a8c0-93ee549dcec9}</v>
                  <v n="ImplicitStartStateType" t="ImplicitStartStateTypes">None</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">"PRG_Statemachine_Preop_ENTRY"</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">"PRG_Statemachine_Preop_ENTRY"</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">"PRG_Statemachine_Preop_DO"</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">"PRG_Statemachine_Preop_DO"</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">true</v>
                  <v n="HasDoAction">true</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"Preop"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <o n="ElementVisualisation" t="UMLStateChartElementVisualisation">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">150</v>
                    <v n="LeftPosition">960</v>
                    <v n="WidthValue">249</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">66</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartElement</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">62</v>
                  <v n="DefaultCellSizeY">32</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{56375e9c-dc75-4f03-b1e8-7503465560d1}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{4d2ac672-37ee-4b10-b8f4-30c19cd79fcb}</v>
                  <v n="ParentGuid">{4f9187be-29d3-40ff-a8c0-93ee549dcec9}</v>
                  <v n="ContainerGuid">{03b9b18d-3155-41e0-a205-42a30c935f65}</v>
                  <v n="ShowedStereotype">{598e1e0c-8ef3-4ee4-8c5b-0b0c243d3121}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">-13447886</v>
                  <v n="ZOrder">97U</v>
                </o>
                <v>03b9b18d-3155-41e0-a205-42a30c935f65</v>
                <o t="UMLStateChartComposite">
                  <v n="AllowCompositeActions">false</v>
                  <v n="ExecuteDoActionsWhenNestedCompositesAreActive">false</v>
                  <o n="ElementVisualisation" t="UMLCompositeVisualisation">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">50</v>
                    <v n="LeftPosition">771</v>
                    <v n="WidthValue">968</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">345</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <l n="Areas" t="ArrayList" cet="UMLArea">
                    <o>
                      <v n="Elementguid">{56375e9c-dc75-4f03-b1e8-7503465560d1}</v>
                      <v n="Name">"Region0"</v>
                      <v n="Position">0</v>
                      <v n="Priority">0</v>
                    </o>
                  </l>
                  <v n="StateChartGuid">{4f9187be-29d3-40ff-a8c0-93ee549dcec9}</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">""</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">""</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">""</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">""</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">false</v>
                  <v n="HasDoAction">false</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"Running"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartComposite</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">150</v>
                  <v n="DefaultCellSizeY">100</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{03b9b18d-3155-41e0-a205-42a30c935f65}</v>
                  <v n="ParentGuid">{4f9187be-29d3-40ff-a8c0-93ee549dcec9}</v>
                  <v n="ContainerGuid">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ShowedStereotype">{5f2f9b07-6cc2-4c9b-bdc5-30a777fea04a}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">-989556</v>
                  <v n="ZOrder">92U</v>
                </o>
                <v>91627098-13d9-4ca9-af41-5429b85b18e8</v>
                <o t="UMLStateChartElement">
                  <v n="StateChartGuid">{4f9187be-29d3-40ff-a8c0-93ee549dcec9}</v>
                  <v n="ImplicitStartStateType" t="ImplicitStartStateTypes">None</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">"PRG_Statemachine_Operation_ENTRY"</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">"PRG_Statemachine_Operation_ENTRY"</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">""</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">""</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">true</v>
                  <v n="HasDoAction">false</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"Operation"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <o n="ElementVisualisation" t="UMLStateChartElementVisualisation">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">320</v>
                    <v n="LeftPosition">1450</v>
                    <v n="WidthValue">268</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">49</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartElement</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">62</v>
                  <v n="DefaultCellSizeY">32</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{56375e9c-dc75-4f03-b1e8-7503465560d1}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{91627098-13d9-4ca9-af41-5429b85b18e8}</v>
                  <v n="ParentGuid">{4f9187be-29d3-40ff-a8c0-93ee549dcec9}</v>
                  <v n="ContainerGuid">{03b9b18d-3155-41e0-a205-42a30c935f65}</v>
                  <v n="ShowedStereotype">{2fb06335-1906-4a49-b662-00bc501a6b5b}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">-13447886</v>
                  <v n="ZOrder">98U</v>
                </o>
              </d>
              <v n="FirstPaint">true</v>
              <v n="NextElementID">0</v>
              <d n="UMLRelationObjects" t="Hashtable" ckt="Guid" cvt="UMLRelation">
                <v>9bb1802f-bb6c-49b9-8217-cd89ec18d1e8</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{4d2ac672-37ee-4b10-b8f4-30c19cd79fcb}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">92U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="InjectedActionCodeBefore">true</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"TRANS_Preop_Ready"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">18</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{f872b14a-0555-4bb5-ab12-654b6f61a846}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{9bb1802f-bb6c-49b9-8217-cd89ec18d1e8}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" />
                    <d n="flagsY" t="Hashtable" />
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">1204</v>
                      <v n="AnchorTopPosition">178</v>
                      <v n="AnchorRelationID">{9bb1802f-bb6c-49b9-8217-cd89ec18d1e8}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">Right</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">2</v>
                      <v n="AnchorLeftPosition">1271</v>
                      <v n="AnchorTopPosition">155</v>
                      <v n="AnchorRelationID">{9bb1802f-bb6c-49b9-8217-cd89ec18d1e8}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">Top</v>
                    </o>
                    <v n="NextAnchorID">2</v>
                    <d n="AnchorPoints" t="Hashtable" ckt="Int32" cvt="UMLAnchorPoint">
                      <v>1</v>
                      <o>
                        <v n="AnchorID">1</v>
                        <v n="AnchorLeftPosition">1271</v>
                        <v n="AnchorTopPosition">178</v>
                        <v n="AnchorRelationID">{9bb1802f-bb6c-49b9-8217-cd89ec18d1e8}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                    </d>
                    <v n="RelationIsLinear">false</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{9bb1802f-bb6c-49b9-8217-cd89ec18d1e8}</v>
                  <v n="RelationGuid">{9bb1802f-bb6c-49b9-8217-cd89ec18d1e8}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">true</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>ab17429b-6526-46a7-aa18-0f07921dee10</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{f872b14a-0555-4bb5-ab12-654b6f61a846}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">92U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="InjectedActionCodeBefore">true</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"GVL_IO.bEnableManualWzw"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">19</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{d8bcd792-7416-4b04-81cc-5288d36a3db3}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{ab17429b-6526-46a7-aa18-0f07921dee10}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>0</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-10</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">1275</v>
                      <v n="AnchorTopPosition">135</v>
                      <v n="AnchorRelationID">{ab17429b-6526-46a7-aa18-0f07921dee10}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">3</v>
                      <v n="AnchorLeftPosition">1455</v>
                      <v n="AnchorTopPosition">145</v>
                      <v n="AnchorRelationID">{ab17429b-6526-46a7-aa18-0f07921dee10}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">3</v>
                    <d n="AnchorPoints" t="Hashtable" ckt="Int32" cvt="UMLAnchorPoint">
                      <v>2</v>
                      <o>
                        <v n="AnchorID">2</v>
                        <v n="AnchorLeftPosition">1455</v>
                        <v n="AnchorTopPosition">115</v>
                        <v n="AnchorRelationID">{ab17429b-6526-46a7-aa18-0f07921dee10}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                      <v>1</v>
                      <o>
                        <v n="AnchorID">1</v>
                        <v n="AnchorLeftPosition">1275</v>
                        <v n="AnchorTopPosition">115</v>
                        <v n="AnchorRelationID">{ab17429b-6526-46a7-aa18-0f07921dee10}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                    </d>
                    <v n="RelationIsLinear">true</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{ab17429b-6526-46a7-aa18-0f07921dee10}</v>
                  <v n="RelationGuid">{ab17429b-6526-46a7-aa18-0f07921dee10}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">2</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>2</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>53a38258-7fb8-4b23-84a7-1d24cf0369bf</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{ee5525d9-045e-430a-80e8-849f90fcfd9d}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">0U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="InjectedActionCodeBefore">true</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"TRANS_Init2_Init"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">21</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{d1aa34d3-82ff-46d3-a87c-3bddaa010424}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{53a38258-7fb8-4b23-84a7-1d24cf0369bf}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" />
                    <d n="flagsY" t="Hashtable" />
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">545</v>
                      <v n="AnchorTopPosition">204</v>
                      <v n="AnchorRelationID">{53a38258-7fb8-4b23-84a7-1d24cf0369bf}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">Left</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">1</v>
                      <v n="AnchorLeftPosition">279</v>
                      <v n="AnchorTopPosition">204</v>
                      <v n="AnchorRelationID">{53a38258-7fb8-4b23-84a7-1d24cf0369bf}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">Right</v>
                    </o>
                    <v n="NextAnchorID">1</v>
                    <d n="AnchorPoints" t="Hashtable" />
                    <v n="RelationIsLinear">true</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{53a38258-7fb8-4b23-84a7-1d24cf0369bf}</v>
                  <v n="RelationGuid">{53a38258-7fb8-4b23-84a7-1d24cf0369bf}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">true</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>5bdd9b27-4a07-4eae-ba70-d78f487bb41d</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{d8bcd792-7416-4b04-81cc-5288d36a3db3}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">92U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="InjectedActionCodeBefore">true</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"TRANS_Ready_Operation"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">9</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{91627098-13d9-4ca9-af41-5429b85b18e8}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{5bdd9b27-4a07-4eae-ba70-d78f487bb41d}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" />
                    <d n="flagsY" t="Hashtable" />
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">1517</v>
                      <v n="AnchorTopPosition">194</v>
                      <v n="AnchorRelationID">{5bdd9b27-4a07-4eae-ba70-d78f487bb41d}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">1</v>
                      <v n="AnchorLeftPosition">1517</v>
                      <v n="AnchorTopPosition">315</v>
                      <v n="AnchorRelationID">{5bdd9b27-4a07-4eae-ba70-d78f487bb41d}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">1</v>
                    <d n="AnchorPoints" t="Hashtable" />
                    <v n="RelationIsLinear">true</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{5bdd9b27-4a07-4eae-ba70-d78f487bb41d}</v>
                  <v n="RelationGuid">{5bdd9b27-4a07-4eae-ba70-d78f487bb41d}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>97270192-79d1-4189-80f1-91299a3d56e7</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{79e2950d-15d4-4eef-892e-5f057e8ea4ef}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">72U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="InjectedActionCodeBefore">true</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"TRANS_Error_Reset"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">7</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{2b796e83-5356-4d20-b83b-8d0e8e6cf8c6}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{97270192-79d1-4189-80f1-91299a3d56e7}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" />
                    <d n="flagsY" t="Hashtable" />
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">1145</v>
                      <v n="AnchorTopPosition">465</v>
                      <v n="AnchorRelationID">{97270192-79d1-4189-80f1-91299a3d56e7}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">1</v>
                      <v n="AnchorLeftPosition">903</v>
                      <v n="AnchorTopPosition">465</v>
                      <v n="AnchorRelationID">{97270192-79d1-4189-80f1-91299a3d56e7}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">1</v>
                    <d n="AnchorPoints" t="Hashtable" />
                    <v n="RelationIsLinear">true</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{97270192-79d1-4189-80f1-91299a3d56e7}</v>
                  <v n="RelationGuid">{97270192-79d1-4189-80f1-91299a3d56e7}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>9e4ab02d-19e8-40e9-bd23-29662e052081</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{d1aa34d3-82ff-46d3-a87c-3bddaa010424}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">94U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="InjectedActionCodeBefore">true</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"TRANS_Init_Init2"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">14</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{ee5525d9-045e-430a-80e8-849f90fcfd9d}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{9e4ab02d-19e8-40e9-bd23-29662e052081}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>0</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>0</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">279</v>
                      <v n="AnchorTopPosition">225</v>
                      <v n="AnchorRelationID">{9e4ab02d-19e8-40e9-bd23-29662e052081}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">3</v>
                      <v n="AnchorLeftPosition">545</v>
                      <v n="AnchorTopPosition">214</v>
                      <v n="AnchorRelationID">{9e4ab02d-19e8-40e9-bd23-29662e052081}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">3</v>
                    <d n="AnchorPoints" t="Hashtable" ckt="Int32" cvt="UMLAnchorPoint">
                      <v>2</v>
                      <o>
                        <v n="AnchorID">2</v>
                        <v n="AnchorLeftPosition">505</v>
                        <v n="AnchorTopPosition">214</v>
                        <v n="AnchorRelationID">{9e4ab02d-19e8-40e9-bd23-29662e052081}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                      <v>1</v>
                      <o>
                        <v n="AnchorID">1</v>
                        <v n="AnchorLeftPosition">505</v>
                        <v n="AnchorTopPosition">225</v>
                        <v n="AnchorRelationID">{9e4ab02d-19e8-40e9-bd23-29662e052081}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                    </d>
                    <v n="RelationIsLinear">true</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{9e4ab02d-19e8-40e9-bd23-29662e052081}</v>
                  <v n="RelationGuid">{9e4ab02d-19e8-40e9-bd23-29662e052081}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>0e66f345-1bce-4151-bbae-aa372ce015c0</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{91627098-13d9-4ca9-af41-5429b85b18e8}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">92U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="InjectedActionCodeBefore">true</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"TRANS_Operation_Finished"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">10</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{fcc12a7a-0758-465a-b3e9-e9ed2b5e6f97}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{0e66f345-1bce-4151-bbae-aa372ce015c0}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-20</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>30</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">1445</v>
                      <v n="AnchorTopPosition">345</v>
                      <v n="AnchorRelationID">{0e66f345-1bce-4151-bbae-aa372ce015c0}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">1</v>
                      <v n="AnchorLeftPosition">1236</v>
                      <v n="AnchorTopPosition">345</v>
                      <v n="AnchorRelationID">{0e66f345-1bce-4151-bbae-aa372ce015c0}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">1</v>
                    <d n="AnchorPoints" t="Hashtable" />
                    <v n="RelationIsLinear">true</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{0e66f345-1bce-4151-bbae-aa372ce015c0}</v>
                  <v n="RelationGuid">{0e66f345-1bce-4151-bbae-aa372ce015c0}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>80a28737-5f83-4d60-a141-aa4323c8e18c</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{ee5525d9-045e-430a-80e8-849f90fcfd9d}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">92U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="InjectedActionCodeBefore">true</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"Global_HMI.PLCAxisEnable"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">17</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{4d2ac672-37ee-4b10-b8f4-30c19cd79fcb}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{80a28737-5f83-4d60-a141-aa4323c8e18c}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-20</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>0</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">615</v>
                      <v n="AnchorTopPosition">203</v>
                      <v n="AnchorRelationID">{80a28737-5f83-4d60-a141-aa4323c8e18c}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">1</v>
                      <v n="AnchorLeftPosition">955</v>
                      <v n="AnchorTopPosition">203</v>
                      <v n="AnchorRelationID">{80a28737-5f83-4d60-a141-aa4323c8e18c}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">1</v>
                    <d n="AnchorPoints" t="Hashtable" />
                    <v n="RelationIsLinear">true</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{80a28737-5f83-4d60-a141-aa4323c8e18c}</v>
                  <v n="RelationGuid">{80a28737-5f83-4d60-a141-aa4323c8e18c}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">2</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">true</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>2</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>be40b8b7-fa3e-4147-8065-4516149660bf</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{fcc12a7a-0758-465a-b3e9-e9ed2b5e6f97}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">92U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="InjectedActionCodeBefore">true</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"FALSE"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">11</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{d8bcd792-7416-4b04-81cc-5288d36a3db3}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{be40b8b7-fa3e-4147-8065-4516149660bf}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>10</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>0</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">985</v>
                      <v n="AnchorTopPosition">315</v>
                      <v n="AnchorRelationID">{be40b8b7-fa3e-4147-8065-4516149660bf}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">4</v>
                      <v n="AnchorLeftPosition">1445</v>
                      <v n="AnchorTopPosition">167</v>
                      <v n="AnchorRelationID">{be40b8b7-fa3e-4147-8065-4516149660bf}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">4</v>
                    <d n="AnchorPoints" t="Hashtable" ckt="Int32" cvt="UMLAnchorPoint">
                      <v>3</v>
                      <o>
                        <v n="AnchorID">3</v>
                        <v n="AnchorLeftPosition">1345</v>
                        <v n="AnchorTopPosition">167</v>
                        <v n="AnchorRelationID">{be40b8b7-fa3e-4147-8065-4516149660bf}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                      <v>2</v>
                      <o>
                        <v n="AnchorID">2</v>
                        <v n="AnchorLeftPosition">1345</v>
                        <v n="AnchorTopPosition">265</v>
                        <v n="AnchorRelationID">{be40b8b7-fa3e-4147-8065-4516149660bf}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                      <v>1</v>
                      <o>
                        <v n="AnchorID">1</v>
                        <v n="AnchorLeftPosition">985</v>
                        <v n="AnchorTopPosition">265</v>
                        <v n="AnchorRelationID">{be40b8b7-fa3e-4147-8065-4516149660bf}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                    </d>
                    <v n="RelationIsLinear">true</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{be40b8b7-fa3e-4147-8065-4516149660bf}</v>
                  <v n="RelationGuid">{be40b8b7-fa3e-4147-8065-4516149660bf}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">2</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>2</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>94578991-7d4d-4ac6-ac3e-2f3810e0f7a4</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{f872b14a-0555-4bb5-ab12-654b6f61a846}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">92U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="InjectedActionCodeBefore">true</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"NOT GVL_IO.bEnableManualWzw AND GVL_FiveX.wzwState = WZW_READY"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">20</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{d8bcd792-7416-4b04-81cc-5288d36a3db3}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{94578991-7d4d-4ac6-ac3e-2f3810e0f7a4}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" />
                    <d n="flagsY" t="Hashtable" />
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">1285</v>
                      <v n="AnchorTopPosition">150</v>
                      <v n="AnchorRelationID">{94578991-7d4d-4ac6-ac3e-2f3810e0f7a4}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">Right</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">1</v>
                      <v n="AnchorLeftPosition">1445</v>
                      <v n="AnchorTopPosition">150</v>
                      <v n="AnchorRelationID">{94578991-7d4d-4ac6-ac3e-2f3810e0f7a4}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">Top</v>
                    </o>
                    <v n="NextAnchorID">1</v>
                    <d n="AnchorPoints" t="Hashtable" />
                    <v n="RelationIsLinear">true</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{94578991-7d4d-4ac6-ac3e-2f3810e0f7a4}</v>
                  <v n="RelationGuid">{94578991-7d4d-4ac6-ac3e-2f3810e0f7a4}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">true</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>d674a88b-7653-49e9-8cee-562e2cc66116</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{fcc12a7a-0758-465a-b3e9-e9ed2b5e6f97}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">92U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="InjectedActionCodeBefore">true</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"TRANS_Ready_Operation"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">12</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{91627098-13d9-4ca9-af41-5429b85b18e8}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{d674a88b-7653-49e9-8cee-562e2cc66116}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" />
                    <d n="flagsY" t="Hashtable" />
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">1236</v>
                      <v n="AnchorTopPosition">336</v>
                      <v n="AnchorRelationID">{d674a88b-7653-49e9-8cee-562e2cc66116}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">1</v>
                      <v n="AnchorLeftPosition">1445</v>
                      <v n="AnchorTopPosition">336</v>
                      <v n="AnchorRelationID">{d674a88b-7653-49e9-8cee-562e2cc66116}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">1</v>
                    <d n="AnchorPoints" t="Hashtable" />
                    <v n="RelationIsLinear">true</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{d674a88b-7653-49e9-8cee-562e2cc66116}</v>
                  <v n="RelationGuid">{d674a88b-7653-49e9-8cee-562e2cc66116}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">true</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>4ba8dc17-653d-4eea-83d3-8fdc67e6d0a0</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{03b9b18d-3155-41e0-a205-42a30c935f65}</v>
                  <v n="HighlightedLine">true</v>
                  <v n="ZOrder">92U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="InjectedActionCodeBefore">true</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"TRANS_Error"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">6</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{79e2950d-15d4-4eef-892e-5f057e8ea4ef}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{4ba8dc17-653d-4eea-83d3-8fdc67e6d0a0}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>30</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>20</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">1225</v>
                      <v n="AnchorTopPosition">390</v>
                      <v n="AnchorRelationID">{4ba8dc17-653d-4eea-83d3-8fdc67e6d0a0}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">1</v>
                      <v n="AnchorLeftPosition">1225</v>
                      <v n="AnchorTopPosition">445</v>
                      <v n="AnchorRelationID">{4ba8dc17-653d-4eea-83d3-8fdc67e6d0a0}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">1</v>
                    <d n="AnchorPoints" t="Hashtable" />
                    <v n="RelationIsLinear">false</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{4ba8dc17-653d-4eea-83d3-8fdc67e6d0a0}</v>
                  <v n="RelationGuid">{4ba8dc17-653d-4eea-83d3-8fdc67e6d0a0}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">ExceptionTransition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>96231ab5-e894-41fe-8033-f11fcc6bca10</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{2b796e83-5356-4d20-b83b-8d0e8e6cf8c6}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">94U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="InjectedActionCodeBefore">true</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"TRANS_Init_Init2"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">16</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{ee5525d9-045e-430a-80e8-849f90fcfd9d}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{96231ab5-e894-41fe-8033-f11fcc6bca10}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" />
                    <d n="flagsY" t="Hashtable" />
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">655</v>
                      <v n="AnchorTopPosition">425</v>
                      <v n="AnchorRelationID">{96231ab5-e894-41fe-8033-f11fcc6bca10}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">2</v>
                      <v n="AnchorLeftPosition">565</v>
                      <v n="AnchorTopPosition">224</v>
                      <v n="AnchorRelationID">{96231ab5-e894-41fe-8033-f11fcc6bca10}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">2</v>
                    <d n="AnchorPoints" t="Hashtable" ckt="Int32" cvt="UMLAnchorPoint">
                      <v>1</v>
                      <o>
                        <v n="AnchorID">1</v>
                        <v n="AnchorLeftPosition">565</v>
                        <v n="AnchorTopPosition">425</v>
                        <v n="AnchorRelationID">{96231ab5-e894-41fe-8033-f11fcc6bca10}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                    </d>
                    <v n="RelationIsLinear">false</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{96231ab5-e894-41fe-8033-f11fcc6bca10}</v>
                  <v n="RelationGuid">{96231ab5-e894-41fe-8033-f11fcc6bca10}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>08538378-36d0-4dd1-95d1-319191f568b4</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{322ae633-3183-4716-b79d-ed73d6d304b5}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">91U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="InjectedActionCodeBefore">true</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">""</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">3</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{d1aa34d3-82ff-46d3-a87c-3bddaa010424}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{08538378-36d0-4dd1-95d1-319191f568b4}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" />
                    <d n="flagsY" t="Hashtable" />
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">115</v>
                      <v n="AnchorTopPosition">15</v>
                      <v n="AnchorRelationID">{08538378-36d0-4dd1-95d1-319191f568b4}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">2</v>
                      <v n="AnchorLeftPosition">60</v>
                      <v n="AnchorTopPosition">175</v>
                      <v n="AnchorRelationID">{08538378-36d0-4dd1-95d1-319191f568b4}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">2</v>
                    <d n="AnchorPoints" t="Hashtable" ckt="Int32" cvt="UMLAnchorPoint">
                      <v>1</v>
                      <o>
                        <v n="AnchorID">1</v>
                        <v n="AnchorLeftPosition">60</v>
                        <v n="AnchorTopPosition">15</v>
                        <v n="AnchorRelationID">{08538378-36d0-4dd1-95d1-319191f568b4}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                    </d>
                    <v n="RelationIsLinear">true</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{08538378-36d0-4dd1-95d1-319191f568b4}</v>
                  <v n="RelationGuid">{08538378-36d0-4dd1-95d1-319191f568b4}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">CompletionTransition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">true</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
              </d>
              <v n="NextRelationID">0</v>
              <v n="DefaultAutomaticLayout">false</v>
              <o n="ClassDiagrammProperties" t="UMLDiagramProperties">
                <v n="ArrayOfPointerToClassPresentation" t="RelationTypes">Empty</v>
                <v n="ArrayOfClassPresentation" t="RelationTypes">Empty</v>
                <v n="ArrayOfInterfacePresentation" t="RelationTypes">Empty</v>
                <v n="ArrayOfInterfaceAggregationPresentation" t="RelationTypes">Empty</v>
                <v n="PointerToClassPresentation" t="RelationTypes">Empty</v>
                <v n="ClassPresentation" t="RelationTypes">Empty</v>
                <v n="InterfacePresentation" t="RelationTypes">Empty</v>
                <v n="InterfaceAggregationPresentation" t="RelationTypes">Empty</v>
                <v n="ShowRoleNames">true</v>
                <v n="ShowCardinalities">true</v>
                <v n="ShowRelationNames">true</v>
                <v n="ShowAttributesinClasses">false</v>
                <v n="ShowMethodsInClasses">false</v>
                <v n="ParametersMaximumLength">20</v>
              </o>
              <v n="IsFastStateDiagram">false</v>
              <l n="StereoTypeProfile" t="ArrayList" />
              <v n="RelationRoleID">21</v>
              <d n="PositionSerialization" t="Hashtable" ckt="Int64" cvt="Guid">
                <v>43</v>
                <v>53a38258-7fb8-4b23-84a7-1d24cf0369bf</v>
                <v>42</v>
                <v>94578991-7d4d-4ac6-ac3e-2f3810e0f7a4</v>
                <v>41</v>
                <v>ab17429b-6526-46a7-aa18-0f07921dee10</v>
                <v>40</v>
                <v>9bb1802f-bb6c-49b9-8217-cd89ec18d1e8</v>
                <v>39</v>
                <v>f872b14a-0555-4bb5-ab12-654b6f61a846</v>
                <v>38</v>
                <v>80a28737-5f83-4d60-a141-aa4323c8e18c</v>
                <v>37</v>
                <v>96231ab5-e894-41fe-8033-f11fcc6bca10</v>
                <v>36</v>
                <v>9e4ab02d-19e8-40e9-bd23-29662e052081</v>
                <v>35</v>
                <v>ee5525d9-045e-430a-80e8-849f90fcfd9d</v>
                <v>34</v>
                <v>ee5525d9-045e-430a-80e8-849f90fcfd9d</v>
                <v>33</v>
                <v>c57d0814-a4ff-4726-8f53-765953fad1a8</v>
                <v>32</v>
                <v>d674a88b-7653-49e9-8cee-562e2cc66116</v>
                <v>31</v>
                <v>be40b8b7-fa3e-4147-8065-4516149660bf</v>
                <v>30</v>
                <v>0e66f345-1bce-4151-bbae-aa372ce015c0</v>
                <v>29</v>
                <v>5bdd9b27-4a07-4eae-ba70-d78f487bb41d</v>
                <v>27</v>
                <v>97270192-79d1-4189-80f1-91299a3d56e7</v>
                <v>26</v>
                <v>4ba8dc17-653d-4eea-83d3-8fdc67e6d0a0</v>
                <v>23</v>
                <v>08538378-36d0-4dd1-95d1-319191f568b4</v>
                <v>21</v>
                <v>2b796e83-5356-4d20-b83b-8d0e8e6cf8c6</v>
                <v>20</v>
                <v>2b796e83-5356-4d20-b83b-8d0e8e6cf8c6</v>
                <v>19</v>
                <v>03b9b18d-3155-41e0-a205-42a30c935f65</v>
                <v>18</v>
                <v>79e2950d-15d4-4eef-892e-5f057e8ea4ef</v>
                <v>17</v>
                <v>79e2950d-15d4-4eef-892e-5f057e8ea4ef</v>
                <v>16</v>
                <v>fcc12a7a-0758-465a-b3e9-e9ed2b5e6f97</v>
                <v>15</v>
                <v>fcc12a7a-0758-465a-b3e9-e9ed2b5e6f97</v>
                <v>14</v>
                <v>904edc38-918f-4ea4-8445-4b537bee8d8d</v>
                <v>13</v>
                <v>91627098-13d9-4ca9-af41-5429b85b18e8</v>
                <v>12</v>
                <v>91627098-13d9-4ca9-af41-5429b85b18e8</v>
                <v>11</v>
                <v>d8bcd792-7416-4b04-81cc-5288d36a3db3</v>
                <v>10</v>
                <v>d8bcd792-7416-4b04-81cc-5288d36a3db3</v>
                <v>9</v>
                <v>4d2ac672-37ee-4b10-b8f4-30c19cd79fcb</v>
                <v>8</v>
                <v>4d2ac672-37ee-4b10-b8f4-30c19cd79fcb</v>
                <v>7</v>
                <v>d1aa34d3-82ff-46d3-a87c-3bddaa010424</v>
                <v>6</v>
                <v>5e145367-436e-446a-ad4e-c2a04f77b02c</v>
                <v>5</v>
                <v>d1aa34d3-82ff-46d3-a87c-3bddaa010424</v>
                <v>4</v>
                <v>ca497a29-fb16-4bf5-b223-07cebf65b464</v>
                <v>3</v>
                <v>322ae633-3183-4716-b79d-ed73d6d304b5</v>
                <v>2</v>
                <v>944604bb-390f-4eb0-93a1-17aa15cc1dac</v>
              </d>
            </o>
          </Data>
          <TypeList>
            <Type n="ArrayList">System.Collections.ArrayList</Type>
            <Type n="ArrowTypes">{812dac4c-85cd-4336-bb2f-f967774b251e}</Type>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="Docked">{7586ffd4-4b2d-494c-aff5-a40d31dac111}</Type>
            <Type n="Double">System.Double</Type>
            <Type n="EditorRestrictions">{1ca7a370-7213-48b2-9df6-3ac7e85f0c68}</Type>
            <Type n="Guid">System.Guid</Type>
            <Type n="Hashtable">System.Collections.Hashtable</Type>
            <Type n="HistoryTypes">{3534dff0-3cd3-4ab6-8e74-b81ff8613005}</Type>
            <Type n="ImplicitStartStateTypes">{159536e2-c3a1-4501-a760-7b5009964f41}</Type>
            <Type n="Int16">System.Int16</Type>
            <Type n="Int32">System.Int32</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="RelationTypes">{f5146002-a332-47c0-9d9a-7997d539e6a9}</Type>
            <Type n="String">System.String</Type>
            <Type n="UInt32">System.UInt32</Type>
            <Type n="UMLAnchorPoint">{610ad96d-085d-4ced-95e0-831f42edefc2}</Type>
            <Type n="UMLArea">{7b0cf5f4-81b9-4f82-abc9-9de087e8469a}</Type>
            <Type n="UMLCompositeVisualisation">{408045ae-deed-4f23-8f67-f77d80b7a749}</Type>
            <Type n="UMLDiagramProperties">{71bc64fb-98e8-4f9a-b2ec-0da66cfaa0a0}</Type>
            <Type n="UMLRelation">{66eb2f12-934d-4c0a-8710-d6fec8d1ff48}</Type>
            <Type n="UMLRelationVisualisation">{79af0d10-00d2-4abe-9c91-6b4e07d4aa1d}</Type>
            <Type n="UMLStateChart">{9b0dd937-6691-44b8-b0c0-27601a5e098a}</Type>
            <Type n="UMLStateChartComposite">{05967c19-34ab-4e26-b363-c32e4509c5dc}</Type>
            <Type n="UMLStateChartDiagramElementVisualisationDot">{573ce27a-c0d4-453b-8ffd-6d125a13ad66}</Type>
            <Type n="UMLStateChartElement">{a9cbb7e7-7aa8-4772-a0f9-efee80bd48b2}</Type>
            <Type n="UMLStateChartElementVisualisation">{861a8beb-602e-4017-bf45-a602984c46fe}</Type>
            <Type n="UMLStateChartPseudoElement">{3569ebb7-c8a3-4ab4-b440-d179b9e0fe9b}</Type>
            <Type n="UMLType">{0197b136-405a-42ee-bb27-fd08b621d0cf}</Type>
          </TypeList>
        </XmlArchive>
      </StateChart>
    </Implementation>
    <Action Name="PRG_Statemachine_Error_DO" Id="{a81d2d2d-d1a2-4795-93f9-0dcbdd7295d6}">
      <Implementation>
        <ST><![CDATA[Global_HMI.PLCAxisEnable := FALSE;]]></ST>
      </Implementation>
    </Action>
    <Action Name="PRG_Statemachine_Error_ENTRY" Id="{c991401a-95f7-4f9c-af91-02bd40ec2f68}">
      <Implementation>
        <ST><![CDATA[GVL_IO.machineStates[0].state := 'ERROR';
GVL_FiveX.MachineStatus := ERROR;
GVL_FiveX.st_LampColor := COLOR_RED;
GVL_FiveX.bError := TRUE;
ErrorType := GVL_FiveX.errorType; ]]></ST>
      </Implementation>
    </Action>
    <Action Name="PRG_Statemachine_Finished_DO" Id="{4ba5d223-9570-45f1-8691-8423d908f496}">
      <Implementation>
        <ST><![CDATA[pBlink(Color1 := COLOR_OFF, Color2 := COLOR_GREEN);	]]></ST>
      </Implementation>
    </Action>
    <Action Name="PRG_Statemachine_Finished_ENTRY" Id="{8faf5321-6a5b-45bb-97be-2df595eb587e}">
      <Implementation>
        <ST><![CDATA[GVL_IO.machineStates[0].state := 'FINISHED';
GVL_FiveX.MachineStatus := FINISHED;]]></ST>
      </Implementation>
    </Action>
    <Action Name="PRG_Statemachine_Init_DO" Id="{b80ea49b-1691-4080-83ec-0e9709e98dd9}">
      <Implementation>
        <ST><![CDATA[GLOBAL_HMI.PLCAxisEnable := FALSE;]]></ST>
      </Implementation>
    </Action>
    <Action Name="PRG_Statemachine_Init_ENTRY" Id="{be123434-c2dc-4308-95d5-7169b7d90959}">
      <Implementation>
        <ST><![CDATA[GVL_IO.machineStates[0].name := 'Machine';
GVL_IO.machineStates[0].state := 'INIT';
GVL_FiveX.MachineStatus := INIT;
GVL_FiveX.st_LampColor := COLOR_YELLOW;
GVL_IO.bKeyPadUnlockManual := TRUE;
]]></ST>
      </Implementation>
    </Action>
    <Action Name="PRG_Statemachine_Init2_ENTRY" Id="{81ad737f-bdfd-464a-8e28-3a49c02bcef6}">
      <Implementation>
        <ST><![CDATA[GVL_IO.bManualPreop := FALSE;]]></ST>
      </Implementation>
    </Action>
    <Action Name="PRG_Statemachine_Operation_ENTRY" Id="{57eb6e40-256a-4dd1-b96f-c7da55b473f6}">
      <Implementation>
        <ST><![CDATA[GVL_IO.machineStates[0].state := 'OPERATION';	
GVL_FiveX.st_LampColor := COLOR_BLUE;
GVL_FiveX.MachineStatus := OPERATION;]]></ST>
      </Implementation>
    </Action>
    <Action Name="PRG_Statemachine_Preop_DO" Id="{6e7a2167-7c64-4144-bd20-2b196a332abe}">
      <Implementation>
        <ST><![CDATA[pBlink(Color1 := COLOR_YELLOW, Color2 := COLOR_GREEN);
]]></ST>
      </Implementation>
    </Action>
    <Action Name="PRG_Statemachine_Preop_ENTRY" Id="{1de43148-9384-4cfa-b081-336c18b2c850}">
      <Implementation>
        <ST><![CDATA[GVL_FiveX.MachineStatus := PREOP;
GVL_FiveX.DoorStatus := MOVESTATE_PREOP;
GVL_FiveX.pneumaticState := PNEU_PREOP;
GVL_FiveX.wzwState := WZW_PREOP;
GVL_IO.machineStates[0].state := 'PREOP';
]]></ST>
      </Implementation>
    </Action>
    <Action Name="PRG_Statemachine_Ready_ENTRY" Id="{f655a16b-45bb-46d9-94fd-ce0812304b1f}">
      <Implementation>
        <ST><![CDATA[GVL_FiveX.MachineStatus := READY;
GVL_IO.machineStates[0].state := 'READY';
GVL_FiveX.st_LampColor := COLOR_GREEN;]]></ST>
      </Implementation>
    </Action>
    <Action Name="PRG_Statemachine_Reset_DO" Id="{709ef85b-ebc4-4de2-94e8-ec34c21cb961}">
      <Implementation>
        <ST><![CDATA[Global_HMI.PLCAxisEnable := FALSE;]]></ST>
      </Implementation>
    </Action>
    <Action Name="PRG_Statemachine_Reset_ENTRY" Id="{24c7342e-4410-4054-b232-7f922950d1a8}">
      <Implementation>
        <ST><![CDATA[GVL_IO.machineStates[0].state := 'RESET';	
GVL_FiveX.MachineStatus := RESET;
pBlink(Color1 := COLOR_YELLOW, Color2 := COLOR_RED);
pWzwHandling(intWzNumber := 0);
bError := FALSE;
GVL_FiveX.bError := FALSE;
GVL_FiveX.bResetButton := FALSE;]]></ST>
      </Implementation>
    </Action>
    <Transition Name="TRANS_Error" Id="{c4a1353b-cb47-4d21-9091-b80bfcbac760}">
      <Implementation>
        <ST><![CDATA[GVL_FiveX.bSafetyFailure OR GVL_FiveX.bError OR NOT GVL_FiveX.bPower OR NOT GLOBAL_HMI.PLCAxisEnable OR GVL_Axes.OneAxisError]]></ST>
      </Implementation>
    </Transition>
    <Transition Name="TRANS_Error_Reset" Id="{6f36dccb-dc8a-4051-8ef2-82ad57bd3bef}">
      <Implementation>
        <ST><![CDATA[GVL_FiveX.bResetButton]]></ST>
      </Implementation>
    </Transition>
    <Transition Name="TRANS_Init_Init2" Id="{a18707ac-7b2c-437e-9d58-e93c6204aaf3}">
      <Implementation>
        <ST><![CDATA[GVL_IO.bManualPreop AND GVL_FiveX.bPower AND GVL_Axes.AllAxesVoltage]]></ST>
      </Implementation>
    </Transition>
    <Transition Name="TRANS_Init2_Init" Id="{34f4c53c-d86f-4235-ac9a-de940261302a}">
      <Implementation>
        <ST><![CDATA[NOT GVL_IO.bManualPreop OR NOT GVL_FiveX.bPower OR NOT GVL_Axes.AllAxesVoltage]]></ST>
      </Implementation>
    </Transition>
    <Transition Name="TRANS_Operation_Finished" Id="{38303d17-68f8-4d42-a1fe-e0db58cd1e05}">
      <Implementation>
        <ST><![CDATA[gpCh[0]^.channel_mc_control.mode_and_state.state_r.state <> 4 AND gpCh[0]^.channel_mc_control.mode_and_state.state_r.state <> 5]]></ST>
      </Implementation>
    </Transition>
    <Transition Name="TRANS_Preop_Ready" Id="{89d631f7-0d58-4742-96a4-0d1f11d3e04d}">
      <Implementation>
        <ST><![CDATA[GVL_FiveX.DoorStatus = MOVESTATE_ENABLE AND GVL_FiveX.pneumaticState = PNEU_READY]]></ST>
      </Implementation>
    </Transition>
    <Transition Name="TRANS_Ready_Operation" Id="{f1ce3301-6ee6-40a6-868c-a677ad37d02a}">
      <Implementation>
        <ST><![CDATA[gpCh[0]^.channel_mc_control.mode_and_state.state_r.state = 4 OR gpCh[0]^.channel_mc_control.mode_and_state.state_r.state = 5 ]]></ST>
      </Implementation>
    </Transition>
    <LineIds Name="PRG_Statemachine.PRG_Statemachine_Error_DO">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="PRG_Statemachine.PRG_Statemachine_Error_ENTRY">
      <LineId Id="2" Count="0" />
      <LineId Id="5" Count="0" />
      <LineId Id="3" Count="0" />
      <LineId Id="6" Count="0" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="PRG_Statemachine.PRG_Statemachine_Finished_DO">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="PRG_Statemachine.PRG_Statemachine_Finished_ENTRY">
      <LineId Id="1" Count="1" />
    </LineIds>
    <LineIds Name="PRG_Statemachine.PRG_Statemachine_Init_DO">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="PRG_Statemachine.PRG_Statemachine_Init_ENTRY">
      <LineId Id="1" Count="0" />
      <LineId Id="3" Count="0" />
      <LineId Id="7" Count="0" />
      <LineId Id="4" Count="2" />
    </LineIds>
    <LineIds Name="PRG_Statemachine.PRG_Statemachine_Init2_ENTRY">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="PRG_Statemachine.PRG_Statemachine_Operation_ENTRY">
      <LineId Id="2" Count="0" />
      <LineId Id="1" Count="0" />
      <LineId Id="3" Count="0" />
    </LineIds>
    <LineIds Name="PRG_Statemachine.PRG_Statemachine_Preop_DO">
      <LineId Id="1" Count="1" />
    </LineIds>
    <LineIds Name="PRG_Statemachine.PRG_Statemachine_Preop_ENTRY">
      <LineId Id="2" Count="1" />
      <LineId Id="1" Count="0" />
      <LineId Id="4" Count="2" />
    </LineIds>
    <LineIds Name="PRG_Statemachine.PRG_Statemachine_Ready_ENTRY">
      <LineId Id="1" Count="2" />
    </LineIds>
    <LineIds Name="PRG_Statemachine.PRG_Statemachine_Reset_DO">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="PRG_Statemachine.PRG_Statemachine_Reset_ENTRY">
      <LineId Id="2" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="3" Count="4" />
    </LineIds>
    <LineIds Name="PRG_Statemachine.TRANS_Error">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="PRG_Statemachine.TRANS_Error_Reset">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="PRG_Statemachine.TRANS_Init_Init2">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="PRG_Statemachine.TRANS_Init2_Init">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="PRG_Statemachine.TRANS_Operation_Finished">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="PRG_Statemachine.TRANS_Preop_Ready">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="PRG_Statemachine.TRANS_Ready_Operation">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>