<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="PRG_FrontDoor" Id="{534c2ff8-8aad-4ec5-a9e2-6ddd2dc29475}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_FrontDoor
VAR
	fbTonClosed					: TON;
	fbTonOpened					: TON;
	bTimer						: BOOL;
	trigFrontDoorClosed			: F_TRIG;
	trigFrontDoorOpened			: F_TRIG;
	intFrontDoorClosedHandling	: INT := 0;
	intFrontDoorOpenedHandling	: INT := 0;
	FrontDoor					: AXIS_REF;					(* axis reference data structure *)
	//state						: EN_MoveState;				(* state machine state *)
	bFirstReset					: BOOL := TRUE;
	PowerFrontDoor				: MC_Power;
	PowerFrontDoorOut			: ST_McOutputs;				
	
	HomeFrontDoor				: MC_Home;
	MoveFrontDoor				: MC_MoveAbsolute;
	MoveFrontDoorSlow			: MC_MoveAbsolute;
	MoveAbsoluteOutFrontDoor	: ST_McOutputs;				
	MoveAbsoluteOutFrontDoorSlow: ST_McOutputs;	
	HomeAbsoluteOutFrontDoor	: ST_McOutputs;
	Reset						: MC_Reset;
	ResetOut 					: ST_McOutputs;				(* debug function block output data *)
	ReadActualPosition			: MC_ReadActualPosition;
	ReadActualPositionOut		: ST_McOutputs;
	ActSetPosition				: MC_SetPosition;
	ActSetPositionOut			: ST_McOutputs;
	MOVEGVL_FiveX: INT;
	DoorStatus_INIT: INT;
	bWarningMessage				: BOOL	:= TRUE;
	bErrorMessage				: BOOL	:= TRUE;
	bReferenceCheck				: BOOL;
	bFirstReferenceCycle		: BOOL := FALSE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Update the axis status at the beginning of each cycle.
//TODO: Add top sensor as a reference point


ActPower();	(* call the power function block *)
ActMove();	(* call the move function block *)
ActReset();	(* call the reset function block *)
ActHome();	(* call the home function block *)
ActReadActualPosition (); 	//Used for HMI
ActSetPosition(Axis := FrontDoor);
FrontDoor.ReadStatus();
fbTonClosed(IN := bTimer, PT := T#1S);
fbTonOpened(IN := bTimer, PT := T#1S);
trigFrontDoorClosed(CLK := GVL_FiveX.bFrontDoorClosed);
trigFrontDoorOpened(CLK := GVL_FiveX.bFrontDoorOpened);
bTimer := trigFrontDoorClosed.CLK;
IF NOT GVL_FiveX.bFrontDoorClosed THEN
	PowerFrontDoor.Enable_Negative := TRUE;
ELSE
	IF GVL_FiveX.DoorStatus = MOVESTATE_PREOP THEN
		CASE intFrontDoorClosedHandling OF
			0:	IF trigFrontDoorClosed.Q THEN		
					intFrontDoorClosedHandling := 1;
				END_IF
			
			1:	IF fbTonClosed.Q THEN	//Waits for timer, disables FrontDoor negative and resets case
					PowerFrontDoor.Enable_Negative := FALSE;
					bTimer := FALSE;
					fbTonClosed.IN := FALSE;
					intFrontDoorClosedHandling := 0;
				END_IF
		END_CASE
	ELSE
		PowerFrontDoor.Enable_Negative := FALSE;
	END_IF
END_IF

IF NOT GVL_FiveX.bFrontDoorOpened THEN
	PowerFrontDoor.Enable_Positive := TRUE;
ELSE
	IF GVL_FiveX.DoorStatus = MOVESTATE_PREOP THEN
		CASE intFrontDoorOpenedHandling OF
			0:	PowerFrontDoor.Enable_Positive := TRUE;
				IF trigFrontDoorOpened.Q THEN		
					intFrontDoorOpenedHandling := 1;
				END_IF
			
			1:	IF fbTonOpened.Q THEN	//Waits for timer, disables FrontDoor negative and resets case
					PowerFrontDoor.Enable_Positive := FALSE;
					bTimer := FALSE;
					fbTonOpened.IN := FALSE;
					intFrontDoorOpenedHandling := 0;
				END_IF
		END_CASE
	ELSE
		PowerFrontDoor.Enable_Positive := FALSE;
	END_IF
END_IF

CASE GVL_FiveX.DoorStatus OF

	MOVESTATE_INIT :
		GVL_IO.machineStates[2].name := 'FrontDoor';
		GVL_IO.machineStates[2].state := 'INIT';
		// Initialize all function blocks
		HomeFrontDoor.Execute := FALSE;
		MoveFrontDoor.Execute := FALSE;
		MoveFrontDoorSlow.Execute := FALSE;
		Reset.Execute := FALSE;
		MoveFrontDoor.Jerk := GVL_FiveX.intDoorJerk;
		MoveFrontDoor.Acceleration := GVL_FiveX.intDoorAcceleration;
		MoveFrontDoor.Deceleration := GVL_FiveX.intDoorDeceleration;
		bFirstReferenceCycle := TRUE;
		IF NOT(bFirstReset) AND GVL_IO.FrontDoorReset THEN
			GVL_FiveX.DoorStatus := MOVESTATE_PREOP;
			GVL_FiveX.bFrontDoorEnableReset := FALSE;
		END_IF
		IF GVL_IO.bStartReferenceDrive THEN
			GVL_FiveX.DoorStatus := MOVESTATE_PREOP;
		END_IF
		
	
	MOVESTATE_PREOP :
		GVL_IO.machineStates[2].state := 'PREOP';
		bReferenceCheck := TRUE;
		GVL_IO.bStartReferenceDrive := FALSE;
		IF GVL_FiveX.bFrontDoorReference THEN
			IF NOT bReferenceDirection THEN
				//GVL_FiveX.bReferencePoint := TRUE;
				GVL_FiveX.intDoorPositionUpFast		:= 40;
				GVL_FiveX.intDoorPositionUpSlow		:= 105;
				GVL_FiveX.intDoorPositionDownFast	:= -750;
				GVL_FiveX.intDoorPostitionDownSlow	:= -810;
			ELSE
				//GVL_FiveX.bReferencePoint := TRUE;
				GVL_FiveX.intDoorPositionUpFast		:= 55;
				GVL_FiveX.intDoorPositionUpSlow		:= 120;
				GVL_FiveX.intDoorPositionDownFast	:= -735;
				GVL_FiveX.intDoorPostitionDownSlow	:= -795;
			END_IF
		ELSIF GVL_FiveX.bFrontDoorOpened THEN
			//GVL_FiveX.bReferencePoint := TRUE;
			GVL_FiveX.intDoorPositionUpFast		:= -60;//850
			GVL_FiveX.intDoorPositionUpSlow		:= 0;//915
			GVL_FiveX.intDoorPositionDownFast	:= -850;//60
			GVL_FiveX.intDoorPostitionDownSlow	:= -915;//0
		ELSE	
			//GVL_FiveX.bReferencePoint := FALSE;
			GVL_FiveX.intDoorPositionUpFast		:= 850;
			GVL_FiveX.intDoorPositionUpSlow		:= 915;
			GVL_FiveX.intDoorPositionDownFast	:= 60;
			GVL_FiveX.intDoorPostitionDownSlow	:= 0;
		END_IF
		IF NOT bFirstReferenceCycle THEN
			IF GVL_FiveX.bFrontDoorClosed THEN
				HomeFrontDoor.bCalibrationCam := FALSE;
			ELSIF GVL_FiveX.bFrontDoorReference THEN
				HomeFrontDoor.bCalibrationCam := FALSE;
			ELSIF GVL_FiveX.bFrontDoorOpened THEN
				HomeFrontDoor.bCalibrationCam := FALSE;
			ELSE
				HomeFrontDoor.bCalibrationCam := TRUE;
			END_IF
		ELSE
			HomeFrontDoor.bCalibrationCam := TRUE;
			bFirstReferenceCycle := FALSE;
		END_IF
		HomeFrontDoor.HomingMode := MC_DefaultHoming;
		IF GVL_FiveX.bReferenceDirection THEN
			HomeFrontDoor.Options.SearchDirection := MC_Direction.MC_Positive_Direction;
			HomeFrontDoor.Options.SyncDirection := MC_Direction.MC_Positive_Direction;
		ELSE
			HomeFrontDoor.Options.SearchDirection := MC_Direction.MC_Positive_Direction;
			HomeFrontDoor.Options.SyncDirection := MC_Direction.MC_Negative_Direction;
		END_IF

		HomeFrontDoor.Options.SearchVelocity := intDoorReferenceVelocity;
		HomeFrontDoor.Options.SyncVelocity := intDoorReferenceVelocity;
		HomeFrontDoor.Options.ReferenceMode := E_EncoderReferenceMode.ENCODERREFERENCEMODE_DEFAULT;
		IF Global_HMI.PLCAxisEnable THEN
			PowerFrontDoor.Enable := TRUE;   //Button HMI Reference Frontdoor
			IF GVL_FiveX.bFrontDoorClosed THEN
				HomeFrontDoor.HomingMode := MC_Direct;
				HomeFrontDoor.Execute := TRUE;
			END_IF
			IF GVL_FiveX.bFrontDoorOpened THEN
				HomeFrontDoor.HomingMode := MC_Direct;
				homeFrontDoor.Execute := TRUE;
			END_IF
			IF HomeFrontDoor.Done THEN
				GVL_FiveX.bFrontDoorEnableReset := FALSE;
				GVL_FiveX.bReferenceDriveDone := TRUE;
				GVL_FiveX.DoorStatus := MOVESTATE_ENABLE;
			END_IF
			IF NOT GVL_IO.bForceStopRefereneDrive THEN
				HomeFrontDoor.Execute := TRUE;
			END_IF
		END_IF
		IF GVL_IO.bForceStopRefereneDrive THEN
			HomeFrontDoor.bCalibrationCam := FALSE;
			GVL_FiveX.bRefenceDriveSkipped := TRUE;
		END_IF
		
	MOVESTATE_ENABLE :
		GVL_IO.machineStates[2].state := 'READY';
		bFirstReset := TRUE;	//needed for Error/Reset Handling
		IF GVL_IO.bForceStopRefereneDrive THEN
			GVL_IO.bForceStopRefereneDrive := FALSE;
			GVL_FiveX.DoorStatus := MOVESTATE_INIT;
		ELSE
			GVL_FiveX.bRefenceDriveSkipped := FALSE;
		END_IF
		GVL_IO.bForceStopRefereneDrive := FALSE;
		IF PLCAxisEnable THEN
			PowerFrontDoor.Enable := TRUE;		
			IF PowerFrontDoor.Status AND GVL_IO.FrontDoorUp AND PLCAxisEnable AND NOT GVL_FiveX.bFrontDoorOpened THEN
				GVL_FiveX.DoorStatus := MOVESTATE_UPWARDS;
			ELSIF PowerFrontDoor.Status AND GVL_IO.FrontDoorDown AND PLCAxisEnable AND NOT GVL_FiveX.bFrontDoorClosed THEN
				GVL_FiveX.DoorStatus := MOVESTATE_DOWNWARDS;
			ELSIF PowerFrontDoor.Error THEN
				GVL_FiveX.DoorStatus := MOVESTATE_ERROR;
			ELSE
				PowerFrontDoor.Enable_Positive := FALSE;
				PowerFrontDoor.Enable_Negative := FALSE;
				// Reset all commands.
				GVL_IO.FrontDoorDown := FALSE;
				GVL_IO.FrontDoorUp := FALSE;
			END_IF
		ELSE
			// Reset all commands.
			PowerFrontDoor.Enable := FALSE;
		END_IF
		IF GVL_IO.bStartReferenceDrive THEN
			GVL_FiveX.DoorStatus := MOVESTATE_PREOP;
		END_IF

	MOVESTATE_UPWARDS :
		GVL_IO.machineStates[2].state := 'UPWARDS';
		MoveFrontDoor.Position := GVL_FiveX.intDoorPositionUpFast;
		MoveFrontDoor.Velocity := GVL_FiveX.intDoorVelocityFast;
		MoveFrontDoor.BufferMode := MC_Buffered;
		MoveFrontDoor.Execute := TRUE;
		IF (MoveFrontDoor.Active AND NOT GVL_IO.FrontDoorUp) OR GVL_FiveX.bFrontDoorOpened OR NOT PLCAxisEnable THEN
			// Axis is executing job but is not yet finished.
			MoveFrontDoor.Execute := FALSE;
			GVL_FiveX.DoorStatus := MOVESTATE_ENABLE;
		ELSIF MoveFrontDoor.Done AND GVL_IO.FrontDoorUp THEN
			// Finished movement.
			MoveFrontDoor.Execute := FALSE;
			GVL_FiveX.DoorStatus := MOVESTATE_UPWARDSSLOW;
		ELSIF MoveFrontDoor.CommandAborted OR MoveFrontDoor.Error THEN
			GVL_FiveX.DoorStatus := MOVESTATE_ERROR;
		END_IF
		IF ReadActualPosition.Position >= GVL_FiveX.intDoorPositionUpFast+5 AND NOT GVL_FiveX.bFrontDoorClosed THEN
			GVL_FiveX.errorType := 'FRONT_DOOR_POSITION_ERROR_UPWARDS';
			GVL_FiveX.bError := TRUE;
			GVL_FiveX.DoorStatus := MOVESTATE_ERROR;
		END_IF

	MOVESTATE_UPWARDSSLOW :
		GVL_IO.machineStates[2].state := 'UPWARDS SLOW';
		MoveFrontDoorSlow.Position := GVL_FiveX.intDoorPositionUpSlow;
		MoveFrontDoorSlow.Velocity := GVL_FiveX.intDoorVelocitySlow;
		MoveFrontDoorSlow.BufferMode := MC_BlendingNext;
		MoveFrontDoorSlow.Execute := TRUE;
		IF (MoveFrontDoorSlow.Active AND NOT GVL_IO.FrontDoorUp) OR GVL_FiveX.bFrontDoorOpened OR NOT PLCAxisEnable THEN
			// Axis is executing job but is not yet finished.
			MoveFrontDoorSlow.Execute := FALSE;
			GVL_FiveX.DoorStatus := MOVESTATE_ENABLE;
		ELSIF MoveFrontDoorSlow.Done AND GVL_IO.FrontDoorUp THEN
			// Finished movement.
			MoveFrontDoorSlow.Execute := FALSE;						
			GVL_IO.FrontDoorUp := FALSE;
			GVL_FiveX.DoorStatus := MOVESTATE_ENABLE;
		ELSIF MoveFrontDoorSlow.CommandAborted OR MoveFrontDoorSlow.Error THEN
			GVL_FiveX.DoorStatus := MOVESTATE_ERROR;
		END_IF
		IF ReadActualPosition.Position >= GVL_FiveX.intDoorPositionUpSlow+1 AND NOT GVL_FiveX.bFrontDoorClosed THEN
			GVL_FiveX.errorType := 'FRONT_DOOR_POSITION_ERROR_UPWARDSSLOW';
			GVL_FiveX.bError := TRUE;
			GVL_FiveX.DoorStatus := MOVESTATE_ERROR;
		END_IF
		
	MOVESTATE_DOWNWARDS :
		GVL_IO.machineStates[2].state := 'DOWNWARDS';
		MoveFrontDoor.Position := GVL_FiveX.intDoorPositionDownFast;
		MoveFrontDoor.Velocity := GVL_FiveX.intDoorVelocityFast;
		MoveFrontDoor.BufferMode := MC_Buffered;
		MoveFrontDoor.Execute := TRUE;
		IF MoveFrontDoor.Active AND NOT GVL_IO.FrontDoorDown OR GVL_FiveX.bFrontDoorClosed OR NOT PLCAxisEnable THEN
			// Axis is executing job but is not yet finished.
			MoveFrontDoor.Execute := FALSE;
			GVL_FiveX.DoorStatus := MOVESTATE_ENABLE;
		ELSIF MoveFrontDoor.Done AND GVL_IO.FrontDoorDown THEN
			// Finished movement.
			MoveFrontDoor.Execute := FALSE;
			GVL_FiveX.DoorStatus := MOVESTATE_DOWNWARDSSLOW;
		ELSIF MoveFrontDoor.CommandAborted OR MoveFrontDoor.Error THEN
			GVL_FiveX.DoorStatus := MOVESTATE_ERROR;
		END_IF
		IF ReadActualPosition.Position <= GVL_FiveX.intDoorPositionDownFast-5 AND NOT GVL_FiveX.bFrontDoorClosed THEN
			GVL_FiveX.errorType := 'FRONT_DOOR_POSITION_ERROR_DOWNWARDS';
			GVL_FiveX.bError := TRUE;
			GVL_FiveX.DoorStatus := MOVESTATE_ERROR;
		END_IF

	MOVESTATE_DOWNWARDSSLOW :
		GVL_IO.machineStates[2].state := 'DOWNWARDS SLOW';
		MoveFrontDoorSlow.Position := GVL_FiveX.intDoorPostitionDownSlow;
		MoveFrontDoorSlow.Velocity := GVL_FiveX.intDoorVelocitySlow;
		MoveFrontDoorSlow.BufferMode := MC_BlendingNext;
		MoveFrontDoorSlow.Execute := TRUE;
		IF MoveFrontDoorSlow.Active AND NOT GVL_IO.FrontDoorDown OR GVL_FiveX.bFrontDoorClosed OR NOT PLCAxisEnable THEN
			// Axis is executing job but is not yet finished.
			MoveFrontDoorSlow.Execute := FALSE;
			GVL_FiveX.DoorStatus := MOVESTATE_ENABLE;
		ELSIF MoveFrontDoorSlow.Done AND GVL_IO.FrontDoorDown THEN
			// Finished movement.
			MoveFrontDoorSlow.Execute := FALSE;
			GVL_IO.FrontDoorDown := FALSE;
			GVL_FiveX.DoorStatus := MOVESTATE_ENABLE;
		ELSIF MoveFrontDoorSlow.CommandAborted OR MoveFrontDoor.Error THEN
			GVL_FiveX.DoorStatus := MOVESTATE_ERROR;
		END_IF
		IF ReadActualPosition.Position <= GVL_FiveX.intDoorPostitionDownSlow-1 AND NOT GVL_FiveX.bFrontDoorClosed THEN
			GVL_FiveX.errorType := 'FRONT_DOOR_POSITION_ERROR_DOWNWARDSSLOW';
			GVL_FiveX.bError := TRUE;
			GVL_FiveX.DoorStatus := MOVESTATE_ERROR;
		END_IF
		
	MOVESTATE_ERROR :
		GVL_IO.machineStates[2].state := 'ERROR';
		IF FrontDoor.Status.Error THEN
			GVL_FiveX.DoorStatus := MOVESTATE_RESET;	(* axis error requires reset *)
		ELSE
			GVL_FiveX.DoorStatus := MOVESTATE_INIT;	(* function block errors don't need a reset *)
		END_IF

	MOVESTATE_RESET :
		GVL_IO.machineStates[2].state := 'RESET';
		bFirstReset := FALSE;
		Reset.Execute := TRUE;
			GVL_FiveX.bFrontDoorEnableReset := TRUE;
			GVL_FiveX.bFrontDoorResetting := TRUE;
		IF Reset.Done THEN
			GVL_FiveX.DoorStatus := MOVESTATE_INIT;
		ELSIF Reset.Error THEN
			GVL_FiveX.DoorStatus := MOVESTATE_INIT; (* can't do anything here *)
		END_IF

END_CASE
]]></ST>
    </Implementation>
    <Action Name="ActHome" Id="{730e9959-9939-4fe6-903c-2c9963e65ea8}">
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeBox">
                      <o>
                        <v n="BoxType">"MC_Home"</v>
                        <o n="Instance" t="Operand">
                          <v n="Operand">"HomeFrontDoor"</v>
                          <v n="Type">"MC_Home"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">2L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <n />
                            <o>
                              <v n="Operand">"HomeAbsoluteOutFrontDoor.Busy"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">4L</v>
                            </o>
                            <o>
                              <v n="Operand">"HomeAbsoluteOutFrontDoor.Active"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">5L</v>
                            </o>
                            <o>
                              <v n="Operand">"HomeAbsoluteOutFrontDoor.CommandAborted"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">6L</v>
                            </o>
                            <o>
                              <v n="Operand">"HomeAbsoluteOutFrontDoor.Error"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">7L</v>
                            </o>
                            <o>
                              <v n="Operand">"HomeAbsoluteOutFrontDoor.ErrorID"</v>
                              <v n="Type">"UDINT"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">8L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems" cet="BoxTreeOperand">
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"FrontDoor"</v>
                              <v n="Type">"AXIS_REF"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">10L</v>
                            </o>
                            <v n="Id">9L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"HomeFrontDoor.Execute"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">12L</v>
                            </o>
                            <v n="Id">11L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"HomeFrontDoor.Position"</v>
                              <v n="Type">"LREAL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">14L</v>
                            </o>
                            <v n="Id">13L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">16L</v>
                            </o>
                            <v n="Id">15L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">18L</v>
                            </o>
                            <v n="Id">17L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"HomeFrontDoor.Options"</v>
                              <v n="Type">"ST_HomingOptions"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">20L</v>
                            </o>
                            <v n="Id">19L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"HomeFrontDoor.bCalibrationCam"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">22L</v>
                            </o>
                            <v n="Id">21L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Axis</v>
                            <v>Execute</v>
                            <v>Position</v>
                            <v>HomingMode</v>
                            <v>BufferMode</v>
                            <v>Options</v>
                            <v>bCalibrationCam</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>AXIS_REF[REF]</v>
                            <v>BOOL</v>
                            <v>LREAL</v>
                            <v>MC_HomingMode</v>
                            <v>MC_BufferMode</v>
                            <v>ST_HomingOptions</v>
                            <v>BOOL</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Done</v>
                            <v>Busy</v>
                            <v>Active</v>
                            <v>CommandAborted</v>
                            <v>Error</v>
                            <v>ErrorID</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>UDINT</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">FunctionBlock</v>
                        <v n="EN">false</v>
                        <v n="ENO">false</v>
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">3L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">1L</v>
                  </o>
                </l2>
                <v n="BranchCounter">0</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
              <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
              <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
              <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
              <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
              <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Action>
    <Action Name="ActMove" Id="{f608e54f-1538-482b-8785-e5c0b4da0c1e}">
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"MoveAbsoluteOutFrontDoor.Done"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">114L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">true</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"MC_MoveAbsolute"</v>
                          <o n="Instance" t="Operand">
                            <v n="Operand">"MoveFrontDoor"</v>
                            <v n="Type">"MC_MoveAbsolute"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">89L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" cet="Operand">
                              <n />
                              <o>
                                <v n="Operand">"MoveAbsoluteOutFrontDoor.Busy"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">91L</v>
                              </o>
                              <o>
                                <v n="Operand">"MoveAbsoluteOutFrontDoor.Active"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">92L</v>
                              </o>
                              <o>
                                <v n="Operand">"MoveAbsoluteOutFrontDoor.CommandAborted"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">93L</v>
                              </o>
                              <o>
                                <v n="Operand">"MoveAbsoluteOutFrontDoor.Error"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">94L</v>
                              </o>
                              <o>
                                <v n="Operand">"MoveAbsoluteOutFrontDoor.ErrorID"</v>
                                <v n="Type">"UDINT"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">95L</v>
                              </o>
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"MoveFrontDoor.Execute"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">97L</v>
                              </o>
                              <v n="Id">96L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"MoveFrontDoor.Position"</v>
                                <v n="Type">"LREAL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">99L</v>
                              </o>
                              <v n="Id">98L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"MoveFrontDoor.Velocity"</v>
                                <v n="Type">"LREAL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">101L</v>
                              </o>
                              <v n="Id">100L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"MoveFrontDoor.Acceleration"</v>
                                <v n="Type">"LREAL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">103L</v>
                              </o>
                              <v n="Id">102L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"MoveFrontDoor.Deceleration"</v>
                                <v n="Type">"LREAL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">105L</v>
                              </o>
                              <v n="Id">104L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"MoveFrontDoor.Jerk"</v>
                                <v n="Type">"LREAL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">107L</v>
                              </o>
                              <v n="Id">106L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"MoveFrontDoor.BufferMode"</v>
                                <v n="Type">"MC_BufferMode"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">109L</v>
                              </o>
                              <v n="Id">108L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">""</v>
                                <n n="Type" />
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">111L</v>
                              </o>
                              <v n="Id">110L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"FrontDoor"</v>
                                <v n="Type">"AXIS_REF"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">113L</v>
                              </o>
                              <v n="Id">112L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Execute</v>
                              <v>Position</v>
                              <v>Velocity</v>
                              <v>Acceleration</v>
                              <v>Deceleration</v>
                              <v>Jerk</v>
                              <v>BufferMode</v>
                              <v>Options</v>
                              <v>Axis</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>LREAL</v>
                              <v>LREAL</v>
                              <v>LREAL</v>
                              <v>LREAL</v>
                              <v>LREAL</v>
                              <v>MC_BufferMode</v>
                              <v>ST_MoveOptions</v>
                              <v>AXIS_REF (VAR_IN_OUT)</v>
                            </l2>
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Done</v>
                              <v>Busy</v>
                              <v>Active</v>
                              <v>CommandAborted</v>
                              <v>Error</v>
                              <v>ErrorID</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>UDINT</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">FunctionBlock</v>
                          <n n="EN" />
                          <n n="ENO" />
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">90L</v>
                        </o>
                        <v n="Id">115L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">88L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"MoveAbsoluteOutFrontDoorSlow.Done"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">84L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">true</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"MC_MoveAbsolute"</v>
                          <o n="Instance" t="Operand">
                            <v n="Operand">"MoveFrontDoorSlow"</v>
                            <v n="Type">"MC_MoveAbsolute"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">59L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" cet="Operand">
                              <n />
                              <o>
                                <v n="Operand">"MoveAbsoluteOutFrontDoorSlow.Busy"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">61L</v>
                              </o>
                              <o>
                                <v n="Operand">"MoveAbsoluteOutFrontDoorSlow.Active"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">62L</v>
                              </o>
                              <o>
                                <v n="Operand">"MoveAbsoluteOutFrontDoorSlow.CommandAborted"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">63L</v>
                              </o>
                              <o>
                                <v n="Operand">"MoveAbsoluteOutFrontDoorSlow.Error"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">64L</v>
                              </o>
                              <o>
                                <v n="Operand">"MoveAbsoluteOutFrontDoorSlow.ErrorID"</v>
                                <v n="Type">"UDINT"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">65L</v>
                              </o>
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"MoveFrontDoorSlow.Execute"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">67L</v>
                              </o>
                              <v n="Id">66L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"MoveFrontDoorSlow.Position"</v>
                                <v n="Type">"LREAL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">69L</v>
                              </o>
                              <v n="Id">68L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"MoveFrontDoorSlow.Velocity"</v>
                                <v n="Type">"LREAL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">71L</v>
                              </o>
                              <v n="Id">70L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"MoveFrontDoor.Acceleration"</v>
                                <v n="Type">"LREAL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">73L</v>
                              </o>
                              <v n="Id">72L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"MoveFrontDoor.Deceleration"</v>
                                <v n="Type">"LREAL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">75L</v>
                              </o>
                              <v n="Id">74L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"MoveFrontDoor.Jerk"</v>
                                <v n="Type">"LREAL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">77L</v>
                              </o>
                              <v n="Id">76L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"MoveFrontDoorSlow.BufferMode"</v>
                                <v n="Type">"MC_BufferMode"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">79L</v>
                              </o>
                              <v n="Id">78L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">""</v>
                                <n n="Type" />
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">81L</v>
                              </o>
                              <v n="Id">80L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"FrontDoor"</v>
                                <v n="Type">"AXIS_REF"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">83L</v>
                              </o>
                              <v n="Id">82L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Execute</v>
                              <v>Position</v>
                              <v>Velocity</v>
                              <v>Acceleration</v>
                              <v>Deceleration</v>
                              <v>Jerk</v>
                              <v>BufferMode</v>
                              <v>Options</v>
                              <v>Axis</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>LREAL</v>
                              <v>LREAL</v>
                              <v>LREAL</v>
                              <v>LREAL</v>
                              <v>LREAL</v>
                              <v>MC_BufferMode</v>
                              <v>ST_MoveOptions</v>
                              <v>AXIS_REF (VAR_IN_OUT)</v>
                            </l2>
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Done</v>
                              <v>Busy</v>
                              <v>Active</v>
                              <v>CommandAborted</v>
                              <v>Error</v>
                              <v>ErrorID</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>UDINT</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">FunctionBlock</v>
                          <n n="EN" />
                          <n n="ENO" />
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">60L</v>
                        </o>
                        <v n="Id">85L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">58L</v>
                  </o>
                </l2>
                <v n="BranchCounter">0</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="BoxTreeAssign">{9873c309-1f09-4ebf-9078-42d8057ef11b}</Type>
              <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
              <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
              <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
              <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
              <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
              <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Action>
    <Action Name="ActPower" Id="{d410a8cc-5a75-46f6-a283-ac52ec2f77ea}">
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"PowerFrontDoorOut.Done"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">21L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">true</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"MC_Power"</v>
                          <o n="Instance" t="Operand">
                            <v n="Operand">"PowerFrontDoor"</v>
                            <v n="Type">"MC_Power"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">3L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" cet="Operand">
                              <n />
                              <o>
                                <v n="Operand">"PowerFrontDoorOut.Busy"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">5L</v>
                              </o>
                              <o>
                                <v n="Operand">"PowerFrontDoorOut.Active"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">6L</v>
                              </o>
                              <o>
                                <v n="Operand">"PowerFrontDoorOut.Error"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">7L</v>
                              </o>
                              <o>
                                <v n="Operand">"PowerFrontDoorOut.ErrorID"</v>
                                <v n="Type">"UDINT"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">8L</v>
                              </o>
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"PowerFrontDoor.Enable"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">10L</v>
                              </o>
                              <v n="Id">9L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"PowerFrontDoor.Enable_Positive"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">12L</v>
                              </o>
                              <v n="Id">11L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"PowerFrontDoor.Enable_Negative"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">14L</v>
                              </o>
                              <v n="Id">13L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"100"</v>
                                <v n="Type">"INT"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">16L</v>
                              </o>
                              <v n="Id">15L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">""</v>
                                <n n="Type" />
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">18L</v>
                              </o>
                              <v n="Id">17L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"FrontDoor"</v>
                                <v n="Type">"AXIS_REF"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">20L</v>
                              </o>
                              <v n="Id">19L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Enable</v>
                              <v>Enable_Positive</v>
                              <v>Enable_Negative</v>
                              <v>Override</v>
                              <v>BufferMode</v>
                              <v>Axis</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>LREAL</v>
                              <v>MC_BufferMode</v>
                              <v>AXIS_REF (VAR_IN_OUT)</v>
                            </l2>
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Status</v>
                              <v>Busy</v>
                              <v>Active</v>
                              <v>Error</v>
                              <v>ErrorID</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>UDINT</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">FunctionBlock</v>
                          <n n="EN" />
                          <n n="ENO" />
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">4L</v>
                        </o>
                        <v n="Id">22L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">2L</v>
                  </o>
                </l2>
                <v n="BranchCounter">0</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="BoxTreeAssign">{9873c309-1f09-4ebf-9078-42d8057ef11b}</Type>
              <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
              <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
              <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
              <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
              <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
              <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Action>
    <Action Name="ActReadActualPosition" Id="{509eca0d-0d78-49c7-8690-3fa43cfec1e3}">
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeBox">
                      <o>
                        <v n="BoxType">"MC_ReadActualPosition"</v>
                        <o n="Instance" t="Operand">
                          <v n="Operand">"ReadActualPosition"</v>
                          <v n="Type">"MC_ReadActualPosition"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">3L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <n />
                            <o>
                              <v n="Operand">"ReadActualPositionOut.Busy"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">5L</v>
                            </o>
                            <o>
                              <v n="Operand">"ReadActualPositionOut.Error"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">6L</v>
                            </o>
                            <o>
                              <v n="Operand">"ReadActualPositionOut.ErrorID"</v>
                              <v n="Type">"UDINT"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">7L</v>
                            </o>
                            <o>
                              <v n="Operand">"GVL_FiveX.intDoorCurrentPosition"</v>
                              <v n="Type">"LREAL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">8L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems" cet="BoxTreeOperand">
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"FrontDoor"</v>
                              <v n="Type">"AXIS_REF"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">10L</v>
                            </o>
                            <v n="Id">9L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"TRUE"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">12L</v>
                            </o>
                            <v n="Id">11L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Axis</v>
                            <v>Enable</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>AXIS_REF[REF]</v>
                            <v>BOOL</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Valid</v>
                            <v>Busy</v>
                            <v>Error</v>
                            <v>ErrorID</v>
                            <v>Position</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>UDINT</v>
                            <v>LREAL</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">FunctionBlock</v>
                        <v n="EN">false</v>
                        <v n="ENO">false</v>
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">4L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">2L</v>
                  </o>
                </l2>
                <v n="BranchCounter">0</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
              <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
              <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
              <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
              <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
              <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Action>
    <Action Name="ActReset" Id="{dfb51a04-cfae-422d-bcdd-e5f577044b71}">
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"ResetOut.Done"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">12L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">true</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"MC_Reset"</v>
                          <o n="Instance" t="Operand">
                            <v n="Operand">"Reset"</v>
                            <v n="Type">"MC_Reset"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">3L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" cet="Operand">
                              <n />
                              <o>
                                <v n="Operand">"ResetOut.Busy"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">5L</v>
                              </o>
                              <o>
                                <v n="Operand">"ResetOut.Error"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">6L</v>
                              </o>
                              <o>
                                <v n="Operand">"ResetOut.ErrorID"</v>
                                <v n="Type">"UDINT"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">7L</v>
                              </o>
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"Reset.Execute"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">9L</v>
                              </o>
                              <v n="Id">8L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"FrontDoor"</v>
                                <v n="Type">"AXIS_REF"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">11L</v>
                              </o>
                              <v n="Id">10L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Execute</v>
                              <v>Axis</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>AXIS_REF (VAR_IN_OUT)</v>
                            </l2>
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Done</v>
                              <v>Busy</v>
                              <v>Error</v>
                              <v>ErrorID</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>UDINT</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">FunctionBlock</v>
                          <n n="EN" />
                          <n n="ENO" />
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">4L</v>
                        </o>
                        <v n="Id">13L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">2L</v>
                  </o>
                </l2>
                <v n="BranchCounter">0</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="BoxTreeAssign">{9873c309-1f09-4ebf-9078-42d8057ef11b}</Type>
              <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
              <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
              <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
              <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
              <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
              <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Action>
    <Action Name="ActSetPosition" Id="{cc2abe1e-1c42-4246-a124-e5d5321c392d}">
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeBox">
                      <o>
                        <v n="BoxType">"MC_SetPosition"</v>
                        <o n="Instance" t="Operand">
                          <v n="Operand">"ActSetPosition"</v>
                          <v n="Type">"MC_SetPosition"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">3L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <n />
                            <o>
                              <v n="Operand">"ActSetPositionOut.Busy"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">5L</v>
                            </o>
                            <o>
                              <v n="Operand">"ActSetPositionOut.Error"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">6L</v>
                            </o>
                            <o>
                              <v n="Operand">"ActSetPositionOut.ErrorID"</v>
                              <v n="Type">"UDINT"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">7L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems" cet="BoxTreeOperand">
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"FrontDoor"</v>
                              <v n="Type">"AXIS_REF"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">9L</v>
                            </o>
                            <v n="Id">8L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"ActSetPosition.Execute"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">11L</v>
                            </o>
                            <v n="Id">10L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"ActSetPosition.Position"</v>
                              <v n="Type">"LREAL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">13L</v>
                            </o>
                            <v n="Id">12L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"FALSE"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">15L</v>
                            </o>
                            <v n="Id">14L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"ActSetPosition.Options"</v>
                              <v n="Type">"ST_SetPositionOptions"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">17L</v>
                            </o>
                            <v n="Id">16L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Axis</v>
                            <v>Execute</v>
                            <v>Position</v>
                            <v>Mode</v>
                            <v>Options</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>AXIS_REF[REF]</v>
                            <v>BOOL</v>
                            <v>LREAL</v>
                            <v>BOOL</v>
                            <v>ST_SetPositionOptions</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Done</v>
                            <v>Busy</v>
                            <v>Error</v>
                            <v>ErrorID</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>UDINT</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">FunctionBlock</v>
                        <v n="EN">false</v>
                        <v n="ENO">false</v>
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">4L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">2L</v>
                  </o>
                </l2>
                <v n="BranchCounter">0</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
              <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
              <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
              <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
              <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
              <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Action>
    <LineIds Name="PRG_FrontDoor">
      <LineId Id="20" Count="0" />
      <LineId Id="510" Count="0" />
      <LineId Id="509" Count="0" />
      <LineId Id="850" Count="0" />
      <LineId Id="481" Count="3" />
      <LineId Id="432" Count="0" />
      <LineId Id="561" Count="0" />
      <LineId Id="994" Count="5" />
      <LineId Id="1006" Count="41" />
      <LineId Id="21" Count="0" />
      <LineId Id="24" Count="2" />
      <LineId Id="882" Count="0" />
      <LineId Id="881" Count="0" />
      <LineId Id="27" Count="0" />
      <LineId Id="309" Count="0" />
      <LineId Id="28" Count="0" />
      <LineId Id="232" Count="0" />
      <LineId Id="30" Count="0" />
      <LineId Id="404" Count="2" />
      <LineId Id="973" Count="0" />
      <LineId Id="685" Count="1" />
      <LineId Id="693" Count="0" />
      <LineId Id="687" Count="3" />
      <LineId Id="31" Count="0" />
      <LineId Id="330" Count="1" />
      <LineId Id="883" Count="0" />
      <LineId Id="729" Count="0" />
      <LineId Id="412" Count="0" />
      <LineId Id="734" Count="0" />
      <LineId Id="838" Count="0" />
      <LineId Id="768" Count="0" />
      <LineId Id="755" Count="2" />
      <LineId Id="737" Count="0" />
      <LineId Id="840" Count="0" />
      <LineId Id="842" Count="3" />
      <LineId Id="841" Count="0" />
      <LineId Id="839" Count="0" />
      <LineId Id="738" Count="0" />
      <LineId Id="924" Count="3" />
      <LineId Id="922" Count="1" />
      <LineId Id="769" Count="0" />
      <LineId Id="752" Count="2" />
      <LineId Id="739" Count="0" />
      <LineId Id="736" Count="0" />
      <LineId Id="975" Count="0" />
      <LineId Id="758" Count="0" />
      <LineId Id="970" Count="0" />
      <LineId Id="759" Count="0" />
      <LineId Id="763" Count="0" />
      <LineId Id="761" Count="0" />
      <LineId Id="958" Count="0" />
      <LineId Id="929" Count="0" />
      <LineId Id="762" Count="0" />
      <LineId Id="760" Count="0" />
      <LineId Id="976" Count="0" />
      <LineId Id="978" Count="1" />
      <LineId Id="977" Count="0" />
      <LineId Id="388" Count="0" />
      <LineId Id="780" Count="0" />
      <LineId Id="787" Count="0" />
      <LineId Id="786" Count="0" />
      <LineId Id="788" Count="0" />
      <LineId Id="783" Count="1" />
      <LineId Id="782" Count="0" />
      <LineId Id="390" Count="2" />
      <LineId Id="385" Count="0" />
      <LineId Id="332" Count="1" />
      <LineId Id="368" Count="0" />
      <LineId Id="563" Count="0" />
      <LineId Id="555" Count="0" />
      <LineId Id="370" Count="0" />
      <LineId Id="988" Count="1" />
      <LineId Id="991" Count="0" />
      <LineId Id="990" Count="0" />
      <LineId Id="371" Count="0" />
      <LineId Id="698" Count="0" />
      <LineId Id="486" Count="0" />
      <LineId Id="372" Count="0" />
      <LineId Id="364" Count="0" />
      <LineId Id="373" Count="0" />
      <LineId Id="430" Count="0" />
      <LineId Id="424" Count="0" />
      <LineId Id="334" Count="0" />
      <LineId Id="462" Count="0" />
      <LineId Id="468" Count="0" />
      <LineId Id="606" Count="0" />
      <LineId Id="467" Count="0" />
      <LineId Id="327" Count="0" />
      <LineId Id="33" Count="0" />
      <LineId Id="884" Count="0" />
      <LineId Id="644" Count="0" />
      <LineId Id="472" Count="0" />
      <LineId Id="475" Count="0" />
      <LineId Id="603" Count="0" />
      <LineId Id="607" Count="1" />
      <LineId Id="474" Count="0" />
      <LineId Id="457" Count="0" />
      <LineId Id="268" Count="0" />
      <LineId Id="218" Count="0" />
      <LineId Id="37" Count="1" />
      <LineId Id="149" Count="1" />
      <LineId Id="39" Count="1" />
      <LineId Id="154" Count="0" />
      <LineId Id="767" Count="0" />
      <LineId Id="766" Count="0" />
      <LineId Id="219" Count="0" />
      <LineId Id="158" Count="1" />
      <LineId Id="41" Count="0" />
      <LineId Id="287" Count="1" />
      <LineId Id="286" Count="0" />
      <LineId Id="269" Count="0" />
      <LineId Id="426" Count="2" />
      <LineId Id="42" Count="1" />
      <LineId Id="885" Count="0" />
      <LineId Id="44" Count="6" />
      <LineId Id="52" Count="0" />
      <LineId Id="161" Count="1" />
      <LineId Id="182" Count="0" />
      <LineId Id="163" Count="0" />
      <LineId Id="53" Count="2" />
      <LineId Id="776" Count="3" />
      <LineId Id="775" Count="0" />
      <LineId Id="164" Count="0" />
      <LineId Id="166" Count="0" />
      <LineId Id="886" Count="0" />
      <LineId Id="167" Count="0" />
      <LineId Id="217" Count="0" />
      <LineId Id="169" Count="7" />
      <LineId Id="181" Count="0" />
      <LineId Id="234" Count="0" />
      <LineId Id="177" Count="2" />
      <LineId Id="69" Count="0" />
      <LineId Id="771" Count="3" />
      <LineId Id="770" Count="0" />
      <LineId Id="165" Count="0" />
      <LineId Id="184" Count="0" />
      <LineId Id="887" Count="0" />
      <LineId Id="185" Count="14" />
      <LineId Id="595" Count="2" />
      <LineId Id="599" Count="0" />
      <LineId Id="594" Count="0" />
      <LineId Id="200" Count="1" />
      <LineId Id="888" Count="0" />
      <LineId Id="216" Count="0" />
      <LineId Id="203" Count="9" />
      <LineId Id="235" Count="0" />
      <LineId Id="213" Count="2" />
      <LineId Id="95" Count="1" />
      <LineId Id="588" Count="0" />
      <LineId Id="593" Count="0" />
      <LineId Id="600" Count="0" />
      <LineId Id="592" Count="0" />
      <LineId Id="601" Count="0" />
      <LineId Id="97" Count="0" />
      <LineId Id="890" Count="0" />
      <LineId Id="634" Count="0" />
      <LineId Id="99" Count="5" />
      <LineId Id="891" Count="0" />
      <LineId Id="643" Count="0" />
      <LineId Id="105" Count="0" />
      <LineId Id="700" Count="1" />
      <LineId Id="106" Count="6" />
      <LineId Id="401" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>